/* @generated by design-spec intake wizard */
/* component: radio */
/* spec: components/powerflex/radio/design-spec.md */
import React, { useState } from "react";
import type { Meta, StoryObj } from "@storybook/react";
import "../../../../components/powerflex-theme.css";

interface RadioProps {
  checked?: boolean;
  size?: "sm" | "md" | "lg" | "xl";
  disabled?: boolean;
  label?: string;
}

const SIZE = {
  sm: 16,
  md: 24,
  lg: 32,
  xl: 40,
};

function Radio({ checked = false, size = "md", disabled = false, label }: RadioProps) {
  const [isChecked, setIsChecked] = useState(checked);
  const trackSize = SIZE[size];
  const indicatorSize = size === "sm" ? 8 : size === "md" ? 12 : size === "lg" ? 16 : 24;
  const focusRingSize = trackSize + 4;

  const trackFill = disabled
    ? isChecked
      ? "var(--radio-track-fill-disabled-checked, #bbbbbb)"
      : "var(--radio-track-fill-disabled-unchecked, #f4f4f4)"
    : isChecked
    ? "var(--radio-track-fill-default-checked, #0076ce)"
    : "var(--radio-track-fill-default-unchecked, #ffffff)";
  const trackStroke = disabled
    ? "var(--radio-track-stroke-disabled, #bbbbbb)"
    : "var(--radio-track-stroke-default, #888888)";

  return (
    <label
      role="radio"
      aria-checked={isChecked}
      aria-disabled={disabled || undefined}
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: "8px",
        cursor: disabled ? "not-allowed" : "pointer",
        position: "relative",
        fontFamily: "var(--typography-font-style-primary, 'Roboto')",
        fontSize: "var(--font-size-body-2, 14px)",
      }}
      onClick={() => !disabled && setIsChecked(!isChecked)}
    >
      <div style={{ position: "relative", width: focusRingSize, height: focusRingSize, display: "flex", alignItems: "center", justifyContent: "center" }}>
        <div
          style={{
            position: "absolute",
            width: focusRingSize,
            height: focusRingSize,
            borderRadius: "9999px",
            border: `1px solid var(--radio-focus-ring, #0076ce)`,
            opacity: isChecked && !disabled ? 1 : 0,
          }}
        />
        <div
          style={{
            width: trackSize,
            height: trackSize,
            borderRadius: "9999px",
            backgroundColor: trackFill,
            border: `1px solid ${trackStroke}`,
            boxSizing: "border-box",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          {isChecked && (
            <div
              style={{
                width: indicatorSize,
                height: indicatorSize,
                borderRadius: "9999px",
                backgroundColor: "var(--radio-indicator-fill, #ffffff)",
              }}
            />
          )}
        </div>
      </div>
      {label && <span>{label}</span>}
    </label>
  );
}

const meta: Meta<typeof Radio> = {
  title: "Spec Generated/Powerflex/Radio",
  component: Radio,
  parameters: {
    layout: "centered",
    docs: {
      description: {
        component:
          "Powerflex Radio per components/powerflex/radio/design-spec.md. Theme: components/powerflex-theme.css.",
      },
    },
  },
  argTypes: {
    checked: { control: "boolean" },
    size: { control: "select", options: ["sm", "md", "lg", "xl"] },
    disabled: { control: "boolean" },
    label: { control: "text" },
  },
  args: {
    checked: true,
    size: "md",
    disabled: false,
    label: "Radio option",
  },
};

export default meta;
type Story = StoryObj<typeof Radio>;

export const SpecAccurateDesign: Story = {
  args: {
    checked: true,
    size: "md",
    disabled: false,
    label: "Radio option",
  },
};

export const Sizes: Story = {
  render: () => (
    <div style={{ display: "flex", gap: "16px", alignItems: "center" }}>
      <Radio checked label="Small" size="sm" />
      <Radio checked label="Medium" size="md" />
      <Radio checked label="Large" size="lg" />
      <Radio checked label="Extra large" size="xl" />
    </div>
  ),
};

export const States: Story = {
  render: () => (
    <div style={{ display: "flex", gap: "16px", alignItems: "center" }}>
      <Radio label="Unchecked" />
      <Radio checked label="Checked" />
      <Radio checked disabled label="Disabled" />
    </div>
  ),
};
