/* @generated by design-spec intake wizard */
/* component: text */
/* spec: components/powerflex/text/design-spec.md */
import React, { useState } from "react";
import type { Meta, StoryObj } from "@storybook/react";
import "../../../../components/powerflex-theme.css";

interface TextInputProps {
  value?: string;
  placeholder?: string;
  size?: "sm" | "md" | "lg";
  disabled?: boolean;
  error?: boolean;
  errorMessage?: string;
}

const SIZE_HEIGHT: Record<string, number> = {
  sm: 24,
  md: 32,
  lg: 40,
};

function StatusIcon({ fill }: { fill: string }) {
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
      <circle cx="8" cy="8" r="7" stroke={fill} strokeWidth="2" />
      <path d="M8 4.5v3.5" stroke={fill} strokeWidth="2" strokeLinecap="round" />
      <path d="M8 10v0" stroke={fill} strokeWidth="2" strokeLinecap="round" />
    </svg>
  );
}

function TextInput({
  value = "",
  placeholder = "Placeholder",
  size = "md",
  disabled = false,
  error = false,
  errorMessage = "Error message",
}: TextInputProps) {
  const [val, setVal] = useState(value);
  const height = SIZE_HEIGHT[size];
  const isEmpty = !val;
  const border = error
    ? "var(--text-input-border-error, #af0000)"
    : "var(--text-input-border-default, #888888)";
  const bg = disabled
    ? "var(--text-input-background-disabled, #f4f4f4)"
    : "var(--text-input-background, #ffffff)";
  const color = disabled
    ? "var(--text-input-text-disabled, #777777)"
    : isEmpty
    ? "var(--text-input-text-placeholder, #888888)"
    : "var(--text-input-text-value, #333333)";

  return (
    <div style={{ display: "flex", flexDirection: "column", width: "240px" }}>
      <div
        style={{
          display: "flex",
          alignItems: "center",
          height,
          padding: "0 var(--text-input-padding-x, 8px)",
          border: `1px solid ${border}`,
          borderRadius: "var(--text-input-radius, 5px)",
          backgroundColor: bg,
          boxSizing: "border-box",
          cursor: disabled ? "not-allowed" : "text",
        }}
      >
        <input
          type="text"
          value={val}
          onChange={(e) => setVal(e.target.value)}
          disabled={disabled}
          aria-invalid={error || undefined}
          placeholder={placeholder}
          style={{
            width: "100%",
            border: "none",
            background: "transparent",
            color,
            fontFamily: "var(--typography-font-style-primary, 'Roboto')",
            fontSize: "var(--font-size-body-2, 14px)",
            lineHeight: "var(--font-line-height-line-height-20, 20px)",
            fontWeight: 400,
            outline: "none",
          }}
        />
      </div>
      {error && (
        <div
          role="alert"
          style={{
            display: "flex",
            alignItems: "center",
            gap: "var(--text-input-error-gap, 8px)",
            padding: "var(--text-input-error-padding-y, 4px) 0",
            color: "var(--text-input-text-error, #af0000)",
            fontFamily: "var(--typography-font-style-primary, 'Roboto')",
            fontSize: "var(--font-size-body-2, 14px)",
          }}
        >
          <StatusIcon fill="var(--text-input-icon-error, #af0000)" />
          {errorMessage}
        </div>
      )}
    </div>
  );
}

const meta: Meta<typeof TextInput> = {
  title: "Spec Generated/Powerflex/Text",
  component: TextInput,
  parameters: {
    layout: "centered",
    docs: {
      description: {
        component:
          "Powerflex Text input per components/powerflex/text/design-spec.md. Theme: components/powerflex-theme.css.",
      },
    },
  },
  argTypes: {
    value: { control: "text" },
    placeholder: { control: "text" },
    size: { control: "select", options: ["sm", "md", "lg"] },
    disabled: { control: "boolean" },
    error: { control: "boolean" },
    errorMessage: { control: "text" },
  },
  args: {
    value: "Example value",
    placeholder: "Placeholder",
    size: "md",
    disabled: false,
    error: false,
    errorMessage: "Error message",
  },
};

export default meta;
type Story = StoryObj<typeof TextInput>;

export const SpecAccurateDesign: Story = {
  args: {
    value: "Example value",
    placeholder: "Placeholder",
    size: "md",
    disabled: false,
    error: false,
  },
};

export const Sizes: Story = {
  render: () => (
    <div style={{ display: "flex", flexDirection: "column", gap: "16px", alignItems: "center" }}>
      <TextInput value="Small" size="sm" />
      <TextInput value="Medium" size="md" />
      <TextInput value="Large" size="lg" />
    </div>
  ),
};

export const States: Story = {
  render: () => (
    <div style={{ display: "flex", flexDirection: "column", gap: "16px", alignItems: "center" }}>
      <TextInput value="Default" />
      <TextInput placeholder="Placeholder" value="" />
      <TextInput value="Disabled" disabled />
      <TextInput value="Error" error errorMessage="This field is required" />
    </div>
  ),
};
