/**
 * Synapse façade — strategy: reexport.
 * IDS implementation: `lib/react/ids/dual-list-box`.
 * Load `components/synapse-theme.css` only (not `ids-theme.css`).
 */
export {
  IdsDualListBox as SynapseDualListBox,
  IdsDualListBoxCompound as SynapseDualListBoxCompound,
  IdsDualListBoxListsParent as SynapseDualListBoxListsParent,
  IdsDualListBoxAvailablePane as SynapseDualListBoxAvailablePane,
  IdsDualListBoxAvailablePaneHeader as SynapseDualListBoxAvailablePaneHeader,
  IdsDualListBoxAvailableMetrics as SynapseDualListBoxAvailableMetrics,
  IdsDualListBoxAvailableListGroup as SynapseDualListBoxAvailableListGroup,
  IdsDualListBoxTransferButtonGroup as SynapseDualListBoxTransferButtonGroup,
  IdsDualListBoxMoveAllRight as SynapseDualListBoxMoveAllRight,
  IdsDualListBoxMoveSelectedRight as SynapseDualListBoxMoveSelectedRight,
  IdsDualListBoxMoveSelectedLeft as SynapseDualListBoxMoveSelectedLeft,
  IdsDualListBoxMoveAllLeft as SynapseDualListBoxMoveAllLeft,
  IdsDualListBoxSelectedPane as SynapseDualListBoxSelectedPane,
  IdsDualListBoxSelectedPaneHeader as SynapseDualListBoxSelectedPaneHeader,
  IdsDualListBoxSelectedMetrics as SynapseDualListBoxSelectedMetrics,
  IdsDualListBoxSelectedListGroup as SynapseDualListBoxSelectedListGroup,
  IdsDualListBoxListItem as SynapseDualListBoxListItem,
  IdsDualListBoxDragHandle as SynapseDualListBoxDragHandle,
  IdsDualListBoxItemContent as SynapseDualListBoxItemContent,
  IdsDualListBoxSelectionCheck as SynapseDualListBoxSelectionCheck,
  type DualListBoxItem as SynapseDualListBoxItem,
  type DualListBoxPane as SynapseDualListBoxPane,
  type DualListBoxTransferAction as SynapseDualListBoxTransferAction,
  type DualListBoxTransferDetail as SynapseDualListBoxTransferDetail,
  type DualListBoxDragDropDetail as SynapseDualListBoxDragDropDetail,
  type DualListBoxItemsChangeDetail as SynapseDualListBoxItemsChangeDetail,
  type DualListBoxMetricsFormat as SynapseDualListBoxMetricsFormat,
  type IdsDualListBoxProps as SynapseDualListBoxProps,
  type IdsDualListBoxSlotName as SynapseDualListBoxSlotName,
  type IdsDualListBoxListsParentProps as SynapseDualListBoxListsParentProps,
  type IdsDualListBoxAvailablePaneProps as SynapseDualListBoxAvailablePaneProps,
  type IdsDualListBoxAvailablePaneHeaderProps as SynapseDualListBoxAvailablePaneHeaderProps,
  type IdsDualListBoxAvailableMetricsProps as SynapseDualListBoxAvailableMetricsProps,
  type IdsDualListBoxAvailableListGroupProps as SynapseDualListBoxAvailableListGroupProps,
  type IdsDualListBoxTransferButtonGroupProps as SynapseDualListBoxTransferButtonGroupProps,
  type IdsDualListBoxMoveButtonProps as SynapseDualListBoxMoveButtonProps,
  type IdsDualListBoxSelectedPaneProps as SynapseDualListBoxSelectedPaneProps,
  type IdsDualListBoxSelectedPaneHeaderProps as SynapseDualListBoxSelectedPaneHeaderProps,
  type IdsDualListBoxSelectedMetricsProps as SynapseDualListBoxSelectedMetricsProps,
  type IdsDualListBoxSelectedListGroupProps as SynapseDualListBoxSelectedListGroupProps,
  type IdsDualListBoxListItemProps as SynapseDualListBoxListItemProps,
  type IdsDualListBoxDragHandleProps as SynapseDualListBoxDragHandleProps,
  type IdsDualListBoxItemContentProps as SynapseDualListBoxItemContentProps,
  type IdsDualListBoxSelectionCheckProps as SynapseDualListBoxSelectionCheckProps,
} from "../../ids/dual-list-box";
