/* @generated by strict-spec-storybook-gate */
/* component: button */
import { applicationConfig, moduleMetadata } from "@storybook/angular";
import { provideZoneChangeDetection } from "@angular/core";
import { SPEC_ACCURATE_DESIGN_STORY } from "../../../compiled/component-contracts/common/story-meta.js";
import { BUTTON_SPEC_ACCURATE_DEFAULTS } from "../../../compiled/component-contracts/ids/button.contract.js";
import { IdsButtonComponent } from "../../../compiled/lib/angular/ids/button/ids-button.component.js";
import { IDS_BUTTON_IMPORTS } from "../../../compiled/lib/angular/ids/button/index.js";
import {
  BUTTON_COMPOSITION_DEMO_TEMPLATE,
  BUTTON_DOCS_DESCRIPTION,
  BUTTON_SOURCE_CODE,
  BUTTON_STORY_SOURCE_CODE,
} from "./ids-button.developer-usage.js";

const DEMO_ICON = "settings-gear-detailed";

/** @type {import("@storybook/angular").Meta<IdsButtonComponent>} */
const meta = {
  title: "Components/IDS/Button",
  component: IdsButtonComponent,
  tags: ["autodocs"],
  decorators: [
    applicationConfig({
      providers: [provideZoneChangeDetection()],
    }),
    moduleMetadata({
      imports: [...IDS_BUTTON_IMPORTS],
    }),
  ],
  parameters: {
    layout: "centered",
    docs: {
      canvas: { sourceState: "open" },
      description: { component: BUTTON_DOCS_DESCRIPTION },
      source: {
        type: "code",
        language: "typescript",
        code: BUTTON_SOURCE_CODE,
      },
    },
  },
  argTypes: {
    variant: { control: "select", options: ["primary", "secondary", "tertiary", "destructive"] },
    size: { control: "select", options: ["sm", "md", "lg"] },
    disabled: { control: "boolean" },
    loading: { control: "boolean" },
    iconOnly: { control: "boolean" },
    ariaLabel: { control: "text" },
  },
};

export default meta;

/** @type {import("@storybook/angular").StoryObj<IdsButtonComponent>} */
export const SpecAccurateDesign = {
  name: SPEC_ACCURATE_DESIGN_STORY,
  parameters: {
    docs: {
      description: {
        story:
          "Spec Accurate Design: primary · large · leading icon + label — composition markup.",
      },
      source: {
        type: "code",
        language: "html",
        code: BUTTON_STORY_SOURCE_CODE,
      },
    },
  },
  render: (args) => ({
    props: args,
    template: BUTTON_COMPOSITION_DEMO_TEMPLATE,
  }),
  args: {
    variant: BUTTON_SPEC_ACCURATE_DEFAULTS.variant,
    size: BUTTON_SPEC_ACCURATE_DEFAULTS.size,
    disabled: BUTTON_SPEC_ACCURATE_DEFAULTS.disabled,
    loading: BUTTON_SPEC_ACCURATE_DEFAULTS.loading,
    iconOnly: BUTTON_SPEC_ACCURATE_DEFAULTS.iconOnly,
    ariaLabel: "",
  },
};

/** @type {import("@storybook/angular").StoryObj<IdsButtonComponent>} */
export const StatesMatrix = {
  render: () => ({
    template: `
      <div style="display: grid; gap: 12px;">
        <div style="display: flex; gap: 10px; flex-wrap: wrap;">
          <ids-button variant="primary" size="lg">Primary</ids-button>
          <ids-button variant="secondary" size="lg">Secondary</ids-button>
          <ids-button variant="tertiary" size="lg">Tertiary</ids-button>
          <ids-button variant="destructive" size="lg">Destructive</ids-button>
        </div>
        <div style="display: flex; gap: 10px; flex-wrap: wrap;">
          <ids-button variant="primary" size="lg" [disabled]="true">Primary</ids-button>
          <ids-button variant="secondary" size="lg" [disabled]="true">Secondary</ids-button>
          <ids-button variant="tertiary" size="lg" [disabled]="true">Tertiary</ids-button>
          <ids-button variant="destructive" size="lg" [disabled]="true">Destructive</ids-button>
        </div>
      </div>
    `,
  }),
};

/** @type {import("@storybook/angular").StoryObj<IdsButtonComponent>} */
export const SizeExamples = {
  render: () => ({
    template: `
      <div style="display: grid; gap: 12px;">
        <div style="display: flex; gap: 10px; flex-wrap: wrap; align-items: center;">
          <ids-button variant="primary" size="sm">Small</ids-button>
          <ids-button variant="primary" size="md">Medium</ids-button>
          <ids-button variant="primary" size="lg">Large</ids-button>
        </div>
        <div style="display: flex; gap: 10px; flex-wrap: wrap; align-items: center;">
          <ids-button variant="secondary" size="sm">
            <ids-icon shapeName="${DEMO_ICON}" variant="mask" />
            Small
          </ids-button>
          <ids-button variant="secondary" size="md">
            <ids-icon shapeName="${DEMO_ICON}" variant="mask" />
            Medium
          </ids-button>
          <ids-button variant="secondary" size="lg">
            <ids-icon shapeName="${DEMO_ICON}" variant="mask" />
            Large
          </ids-button>
        </div>
        <div style="display: flex; gap: 10px; flex-wrap: wrap; align-items: center;">
          <ids-button variant="tertiary" size="md" [iconOnly]="true" ariaLabel="Settings medium">
            <ids-icon shapeName="${DEMO_ICON}" variant="mask" />
          </ids-button>
          <ids-button variant="tertiary" size="lg" [iconOnly]="true" ariaLabel="Settings large">
            <ids-icon shapeName="${DEMO_ICON}" variant="mask" />
          </ids-button>
        </div>
      </div>
    `,
  }),
};

/** @type {import("@storybook/angular").StoryObj<IdsButtonComponent>} */
export const TypographyBody2 = {
  parameters: {
    docs: {
      description: {
        story:
          "Body 2 typography from Figma (41894:116183 / 9662:25120): 14/20, weight 400, Roboto primary.",
      },
    },
  },
  render: () => ({
    template: `
      <div style="display: grid; gap: 8px;">
        <ids-button variant="primary" size="lg">Body 2 — 14/20 / 400</ids-button>
        <p
          style="
            margin: 0;
            font-family: var(--typography-font-style-primary, 'Roboto', sans-serif);
            font-size: var(--font-size-body-2);
            line-height: var(--font-line-height-line-height-20);
            font-weight: 400;
          "
        >
          Reference text using the same Body 2 tokens as the button label.
        </p>
      </div>
    `,
  }),
};

/** @type {import("@storybook/angular").StoryObj<IdsButtonComponent>} */
export const IconComposition = {
  name: "Icon Composition",
  render: () => ({
    template: `
      <div style="display: flex; gap: 10px; flex-wrap: wrap;">
        <ids-button variant="primary" size="lg">
          <ids-icon shapeName="${DEMO_ICON}" variant="mask" />
          Button
        </ids-button>
        <ids-button variant="secondary" size="lg">
          <ids-icon shapeName="${DEMO_ICON}" variant="mask" />
          Button
        </ids-button>
        <ids-button variant="tertiary" size="lg">
          <ids-icon shapeName="${DEMO_ICON}" variant="mask" />
          Button
        </ids-button>
        <ids-button variant="primary" size="lg" [iconOnly]="true" ariaLabel="Settings">
          <ids-icon shapeName="${DEMO_ICON}" variant="mask" />
        </ids-button>
      </div>
    `,
  }),
};

/** @type {import("@storybook/angular").StoryObj<IdsButtonComponent>} */
export const Loading = {
  render: () => ({
    template: `
      <div style="display: flex; gap: 10px; flex-wrap: wrap;">
        <ids-button variant="primary" size="lg" [loading]="true">Primary</ids-button>
        <ids-button variant="secondary" size="lg" [loading]="true">Secondary</ids-button>
        <ids-button variant="tertiary" size="lg" [loading]="true">
          <ids-icon shapeName="${DEMO_ICON}" variant="mask" />
          Tertiary
        </ids-button>
      </div>
    `,
  }),
};
