/**
 * Synapse façade — strategy: reexport.
 * IDS implementation: `lib/react/ids/get-started`.
 * Load `components/synapse-theme.css` only (not `ids-theme.css`).
 */
export {
  IdsGetStarted as SynapseGetStarted,
  IdsGetStartedCompound as SynapseGetStartedCompound,
  IdsGetStartedHeroHeader as SynapseGetStartedHeroHeader,
  IdsGetStartedHeroBackground as SynapseGetStartedHeroBackground,
  IdsGetStartedHeroShadowBand as SynapseGetStartedHeroShadowBand,
  IdsGetStartedHeroHoneycomb as SynapseGetStartedHeroHoneycomb,
  IdsGetStartedMastheadSlot as SynapseGetStartedMastheadSlot,
  IdsGetStartedHeroTitle as SynapseGetStartedHeroTitle,
  IdsGetStartedHeroSubtitle as SynapseGetStartedHeroSubtitle,
  IdsGetStartedContainer as SynapseGetStartedContainer,
  IdsGetStartedCardTrack as SynapseGetStartedCardTrack,
  IdsGetStartedCardAnchor as SynapseGetStartedCardAnchor,
  IdsGetStartedCard as SynapseGetStartedCard,
  IdsGetStartedCardIconBadge as SynapseGetStartedCardIconBadge,
  IdsGetStartedCardTitleBand as SynapseGetStartedCardTitleBand,
  IdsGetStartedCardContentPanel as SynapseGetStartedCardContentPanel,
  IdsGetStartedCardDescription as SynapseGetStartedCardDescription,
  IdsGetStartedCardNote as SynapseGetStartedCardNote,
  IdsGetStartedCardConfigureButton as SynapseGetStartedCardConfigureButton,
  IdsGetStartedSkipButton as SynapseGetStartedSkipButton,
  IdsGetStartedOverflowEdge as SynapseGetStartedOverflowEdge,
  IdsGetStartedOverflowGradient as SynapseGetStartedOverflowGradient,
  IdsGetStartedOverflowArrow as SynapseGetStartedOverflowArrow,
  IdsGetStartedOverflowNavButton as SynapseGetStartedOverflowNavButton,
  type IdsGetStartedProps as SynapseGetStartedProps,
  type IdsGetStartedCardInput as SynapseGetStartedCardInput,
  type IdsGetStartedCardState as SynapseGetStartedCardState,
  type IdsGetStartedOverflowPage as SynapseGetStartedOverflowPage,
  type IdsGetStartedOverflowSide as SynapseGetStartedOverflowSide,
  type IdsGetStartedMastheadProps as SynapseGetStartedMastheadProps,
  type IdsGetStartedHeroHeaderProps as SynapseGetStartedHeroHeaderProps,
  type IdsGetStartedHeroBackgroundProps as SynapseGetStartedHeroBackgroundProps,
  type IdsGetStartedHeroShadowBandProps as SynapseGetStartedHeroShadowBandProps,
  type IdsGetStartedHeroHoneycombProps as SynapseGetStartedHeroHoneycombProps,
  type IdsGetStartedMastheadSlotProps as SynapseGetStartedMastheadSlotProps,
  type IdsGetStartedHeroTitleProps as SynapseGetStartedHeroTitleProps,
  type IdsGetStartedHeroSubtitleProps as SynapseGetStartedHeroSubtitleProps,
  type IdsGetStartedContainerProps as SynapseGetStartedContainerProps,
  type IdsGetStartedCardTrackProps as SynapseGetStartedCardTrackProps,
  type IdsGetStartedCardAnchorProps as SynapseGetStartedCardAnchorProps,
  type IdsGetStartedCardProps as SynapseGetStartedCardProps,
  type IdsGetStartedCardIconBadgeProps as SynapseGetStartedCardIconBadgeProps,
  type IdsGetStartedCardTitleBandProps as SynapseGetStartedCardTitleBandProps,
  type IdsGetStartedCardContentPanelProps as SynapseGetStartedCardContentPanelProps,
  type IdsGetStartedCardDescriptionProps as SynapseGetStartedCardDescriptionProps,
  type IdsGetStartedCardNoteProps as SynapseGetStartedCardNoteProps,
  type IdsGetStartedCardConfigureButtonProps as SynapseGetStartedCardConfigureButtonProps,
  type IdsGetStartedSkipButtonProps as SynapseGetStartedSkipButtonProps,
  type IdsGetStartedOverflowEdgeProps as SynapseGetStartedOverflowEdgeProps,
  type IdsGetStartedOverflowGradientProps as SynapseGetStartedOverflowGradientProps,
  type IdsGetStartedOverflowArrowProps as SynapseGetStartedOverflowArrowProps,
  type IdsGetStartedOverflowNavButtonProps as SynapseGetStartedOverflowNavButtonProps,
} from "../../ids/get-started";
