/* @generated by strict-spec-storybook-gate */
/* component: alert */
/* spec_hash: 015b2eb7f28d767852eab46c9ac0f371b98fe79ab8bcde4cadd4cd2a17bc9f4e */
import { applicationConfig, moduleMetadata } from "@storybook/angular";
import { provideZoneChangeDetection } from "@angular/core";
import { SPEC_ACCURATE_DESIGN_STORY } from "../../../compiled/component-contracts/common/story-meta.js";
import {
  ALERT_SPEC_ACCURATE_DEFAULTS,
} from "../../../compiled/component-contracts/ids/alert.contract.js";
import { IdsAlertComponent } from "../../../compiled/lib/angular/ids/alert/ids-alert.component.js";
import { IDS_ALERT_IMPORTS } from "../../../compiled/lib/angular/ids/alert/index.js";
import {
  ALERT_COMPOSITION_DEMO_TEMPLATE,
  ALERT_DOCS_DESCRIPTION,
  ALERT_MULTIPLE_GROUP_SOURCE_CODE,
  ALERT_MULTIPLE_GROUP_TEMPLATE,
  ALERT_INLINE_COMPACT_TEMPLATE,
  ALERT_INLINE_DETAILED_ALL_DETAILS_SOURCE_CODE,
  ALERT_INLINE_DETAILED_ALL_DETAILS_TEMPLATE,
  ALERT_SOURCE_CODE,
  ALERT_STORY_SOURCE_CODE,
} from "./ids-alert.developer-usage.js";

/** @type {import("@storybook/angular").Meta<IdsAlertComponent>} */
const meta = {
  title: "Components/IDS/Alert",
  component: IdsAlertComponent,
  tags: ["autodocs"],
  decorators: [
    applicationConfig({
      providers: [provideZoneChangeDetection()],
    }),
    moduleMetadata({
      imports: [...IDS_ALERT_IMPORTS],
    }),
  ],
  parameters: {
    layout: "padded",
    docs: {
      canvas: { sourceState: "open" },
      description: { component: ALERT_DOCS_DESCRIPTION },
      source: {
        type: "code",
        language: "typescript",
        code: ALERT_SOURCE_CODE,
      },
    },
  },
  argTypes: {
    display: { control: "select", options: ["global", "inline"] },
    severity: { control: "select", options: ["informational", "success", "warning-minor", "warning-major", "critical"] },
    density: { control: "select", options: ["compact", "detailed"] },
    messageText: { control: "text" },
    title: { control: "text" },
    linkLabel: { control: "text" },
    linkHref: { control: "text" },
    actionLabel: { control: "text" },
    dismissible: { control: "boolean" },
  },
};

export default meta;

/** @type {import("@storybook/angular").StoryObj<IdsAlertComponent>} */
export const SpecAccurateDesign = {
  name: SPEC_ACCURATE_DESIGN_STORY,
  parameters: {
    docs: {
      description: {
        story:
          "Spec Accurate Design: inline · informational · compact · dismissible — composition markup with `ids-alert-message`.",
      },
      source: {
        type: "code",
        language: "html",
        code: ALERT_STORY_SOURCE_CODE,
      },
    },
  },
  render: (args) => ({
    props: {
      ...args,
      dismiss: () => {
        args.dismiss?.();
      },
    },
    template: ALERT_COMPOSITION_DEMO_TEMPLATE,
  }),
  args: {
    display: ALERT_SPEC_ACCURATE_DEFAULTS.display,
    severity: ALERT_SPEC_ACCURATE_DEFAULTS.severity,
    density: ALERT_SPEC_ACCURATE_DEFAULTS.density,
    messageText: ALERT_SPEC_ACCURATE_DEFAULTS.message,
    dismissible: ALERT_SPEC_ACCURATE_DEFAULTS.dismissible,
    title: "",
    linkLabel: "",
    linkHref: "",
    actionLabel: "",
  },
};

/** @type {import("@storybook/angular").StoryObj<IdsAlertComponent>} */
export const MultipleAlerts = {
  name: "Multiple Alerts (Global Carousel)",
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        story:
          "Global multi-alert composition: `ids-alert-group` owns carousel state and renders one internal `ids-alert` banner bound to the active `ids-alert-item` (maps to Clarity `clr-alerts` + pager).",
      },
      source: {
        type: "code",
        language: "html",
        code: ALERT_MULTIPLE_GROUP_SOURCE_CODE,
      },
    },
  },
  render: () => ({
    template: ALERT_MULTIPLE_GROUP_TEMPLATE,
  }),
};

/** @type {import("@storybook/angular").StoryObj<IdsAlertComponent>} */
export const InlineCompactStates = {
  name: "Inline Compact States",
  render: () => ({
    template: ALERT_INLINE_COMPACT_TEMPLATE,
  }),
};

/** @type {import("@storybook/angular").StoryObj<IdsAlertComponent>} */
export const InlineDetailedAllDetails = {
  name: "Inline Detailed / All Details (Figma 11946:230644)",
  parameters: {
    docs: {
      description: {
        story:
          "Detailed critical inline: title + message + link + outlined action. Critical inline never shows dismiss.",
      },
      source: {
        type: "code",
        language: "html",
        code: ALERT_INLINE_DETAILED_ALL_DETAILS_SOURCE_CODE,
      },
    },
  },
  render: () => ({
    template: ALERT_INLINE_DETAILED_ALL_DETAILS_TEMPLATE,
  }),
};