export {
  IdsModal,
  IdsModalClose,
  IdsModalHeader,
  IdsModalTitle,
  IdsModalDescription,
  IdsModalTabs,
  IdsModalContent,
  IdsModalFooter,
  type IdsModalProps,
  type IdsModalCloseProps,
  type IdsModalHeaderProps,
  type IdsModalTitleProps,
  type IdsModalDescriptionProps,
  type IdsModalTabsProps,
  type IdsModalContentProps,
  type IdsModalFooterProps,
  type IdsModalScenario,
  type IdsModalType,
  type IdsModalSize,
  type IdsModalLayer,
  type IdsModalPage,
} from "./IdsModal";
export { default } from "./IdsModal";
