import fs from "node:fs";
import path from "node:path";
import { IDS_THEME_PATH, PROGRAMMES, REPO_ROOT } from "../paths.js";
import { readCatalog } from "../tokens/store.js";
import { validateCatalog } from "../validation/validate.js";

function cssValue(value) {
  return String(value).replace(/\s+/g, " ").trim();
}

export function renderIdsTheme(catalog) {
  const themes = catalog.themes ?? [];
  const tokens = catalog.tokens ?? [];
  const groups = [];
  for (const token of tokens) {
    const last = groups[groups.length - 1];
    if (!last || last.group !== token.group) groups.push({ group: token.group, tokens: [token] });
    else last.tokens.push(token);
  }
  const lightLines = [];
  for (const bucket of groups) {
    lightLines.push(`  /* --- ${bucket.group} --- */`);
    for (const token of bucket.tokens) {
      lightLines.push(`  ${token.name}: ${cssValue(token.values.light)};`);
    }
  }
  const extra = themes.filter((theme) => !theme.default);
  const extraBlocks = extra.map((theme) => {
    const lines = [];
    for (const token of tokens) {
      const own = token.values[theme.id];
      if (own == null || String(own).trim() === "" || own === token.values.light) continue;
      lines.push(`  ${token.name}: ${cssValue(own)};`);
    }
    return `html[data-design-system="ids"][data-theme="${theme.id}"], body[data-design-system="ids"][data-theme="${theme.id}"] {\n${lines.join("\n")}\n}`;
  });
  const source = catalog.source?.figmaLibrary ? `\n * Figma library: ${catalog.source.figmaLibrary}` : "";
  return `/*
 * IDS Design System — Global Theme Tokens
 * Generated by DTM from DTM/records/catalog.json.
 * Default theme: light. Other themes emit only values that differ from light.${source}
 * Scoped: html/body[data-design-system="ids"] (+ [data-theme]).
 */

html[data-design-system="ids"], body[data-design-system="ids"] {
${lightLines.join("\n")}
}

${extraBlocks.filter((block) => !block.endsWith("{\n}")).join("\n\n")}
`;
}

export function buildIdsTheme({ write = false } = {}) {
  const catalog = readCatalog();
  const validation = validateCatalog(catalog);
  if (!validation.ok) return { status: "rejected", errors: validation.errors };
  const css = renderIdsTheme(catalog);
  if (write) fs.writeFileSync(IDS_THEME_PATH, css);
  return { status: "built", css, path: write ? "components/ids-theme.css" : null };
}

function splitBlocks(css) {
  const blocks = [];
  const re = /([^{}@]+)\{([^{}]*)\}/g;
  let match;
  while ((match = re.exec(css))) {
    const selector = match[1].trim();
    const body = match[2];
    const decls = [];
    for (const line of body.split("\n")) {
      const prop = line.match(/^\s*(--[\w-]+)\s*:\s*([^;]+);/);
      if (prop) decls.push({ name: prop[1], value: prop[2].trim() });
    }
    if (!decls.length) continue;
    const theme = /data-theme\s*=\s*["']dark["']/.test(selector) ? "dark" : "light";
    blocks.push({ selector, theme, decls });
  }
  return blocks;
}

export function validateProgrammeFiles() {
  const catalog = readCatalog();
  const byName = new Map(catalog.tokens.map((token) => [token.name, token]));
  const reports = [];
  for (const [programme, config] of Object.entries(PROGRAMMES)) {
    for (const file of config.files) {
      if (!fs.existsSync(file)) continue;
      const css = fs.readFileSync(file, "utf8");
      const blocks = splitBlocks(css);
      const seen = new Set();
      const findings = [];
      for (const block of blocks) {
        for (const decl of block.decls) {
          seen.add(decl.name);
          const token = byName.get(decl.name);
          if (!token) {
            findings.push({ name: decl.name, status: "programme-local", theme: block.theme, value: decl.value });
            continue;
          }
          const expected = token.values[block.theme] ?? token.values.light;
          if (decl.value === expected) {
            findings.push({ name: decl.name, status: "in-sync", theme: block.theme, value: decl.value });
          } else {
            findings.push({
              name: decl.name,
              status: "override",
              theme: block.theme,
              value: decl.value,
              catalogValue: expected,
            });
          }
        }
      }
      let missing = 0;
      for (const token of catalog.tokens) {
        if (!seen.has(token.name)) missing += 1;
      }
      const counts = { "in-sync": 0, override: 0, "programme-local": 0, missing };
      for (const finding of findings) counts[finding.status] += 1;
      reports.push({
        programme,
        file: path.relative(REPO_ROOT, file),
        counts,
        findings,
      });
    }
  }
  return reports;
}

export function stripCustomProperty(css, name) {
  const escaped = String(name).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return String(css).replace(new RegExp(`^[ \\t]*${escaped}\\s*:[^;]*;\\r?\\n`, "gm"), "");
}

function matchingParen(text, openIndex) {
  let depth = 0;
  for (let index = openIndex; index < text.length; index += 1) {
    if (text[index] === "(") depth += 1;
    else if (text[index] === ")") {
      depth -= 1;
      if (depth === 0) return index;
    }
  }
  return -1;
}

export function replaceTokenVar(text, from, to, fallbackValue) {
  const source = String(text);
  const needle = "var(";
  const nextValue = fallbackValue == null ? "" : String(fallbackValue).trim();
  let out = "";
  let index = 0;
  while (index < source.length) {
    const start = source.indexOf(needle, index);
    if (start < 0) {
      out += source.slice(index);
      break;
    }
    const open = start + needle.length - 1;
    const close = matchingParen(source, open);
    if (close < 0) {
      out += source.slice(index);
      break;
    }
    out += source.slice(index, start);
    const inner = source.slice(open + 1, close);
    const match = inner.match(/^\s*(--[A-Za-z0-9-]+)([\s\S]*)$/);
    if (match && match[1] === from) {
      const hasFallback = /^\s*,/.test(match[2]);
      out += hasFallback && nextValue ? `var(${to}, ${nextValue})` : `var(${to}${hasFallback ? match[2] : ""})`;
    } else {
      out += source.slice(start, close + 1);
    }
    index = close + 1;
  }
  return out;
}

function upsertBlock(block, name, value) {
  const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const existing = new RegExp(`^([ \\t]*)${escaped}\\s*:[^;]*;`, "m");
  if (existing.test(block)) return block.replace(existing, `$1${name}: ${cssValue(value)};`);
  const close = block.lastIndexOf("}");
  if (close < 0) return `${block}\n  ${name}: ${cssValue(value)};\n`;
  return `${block.slice(0, close)}  ${name}: ${cssValue(value)};\n${block.slice(close)}`;
}

export function upsertIdsThemeToken(name, values, css = fs.readFileSync(IDS_THEME_PATH, "utf8")) {
  const marker = 'data-theme="dark"';
  const at = css.indexOf(marker);
  const light = String(values.light ?? "").trim();
  let next = css;
  if (light) {
    const head = at < 0 ? next : next.slice(0, at);
    const tail = at < 0 ? "" : next.slice(at);
    next = upsertBlock(head, name, light) + tail;
  }
  const darkAt = next.indexOf(marker);
  const dark = values.dark == null ? "" : String(values.dark).trim();
  if (dark && dark !== light && darkAt >= 0) {
    next = next.slice(0, darkAt) + upsertBlock(next.slice(darkAt), name, dark);
  }
  return next;
}

export function writeIdsThemeToken(name, values) {
  const next = upsertIdsThemeToken(name, values);
  fs.writeFileSync(IDS_THEME_PATH, next);
  return next;
}

export function removeIdsThemeToken(name) {
  const next = stripCustomProperty(fs.readFileSync(IDS_THEME_PATH, "utf8"), name);
  fs.writeFileSync(IDS_THEME_PATH, next);
  return next;
}

function patchBlock(body, name, value) {
  const line = new RegExp(`(^\\s*${name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*:\\s*)([^;]+)(;)`, "m");
  if (line.test(body)) return { body: body.replace(line, `$1${value}$3`), patched: true };
  const insertion = `\n  ${name}: ${value};`;
  return { body: `${body.replace(/\s*$/, "")}${insertion}\n`, patched: false, appended: true };
}

export function patchProgrammeToken(programme, name, values) {
  const config = PROGRAMMES[programme];
  if (!config) return { status: "rejected", errors: [{ field: "programme", message: "Unknown programme." }] };
  const catalog = readCatalog();
  const token = catalog.tokens.find((item) => item.name === name);
  if (!token) {
    return { status: "rejected", errors: [{ field: "name", message: "Name is not in the catalog. Add it as a common token first." }] };
  }
  const written = [];
  for (const file of config.files) {
    if (!fs.existsSync(file)) continue;
    const css = fs.readFileSync(file, "utf8");
    const re = /([^{}@]+)\{([^{}]*)\}/g;
    const matches = [...css.matchAll(re)];
    const appended = { light: false, dark: false };
    let next = "";
    let cursor = 0;
    for (const match of matches) {
      next += css.slice(cursor, match.index);
      const selector = match[1];
      const theme = /data-theme\s*=\s*["']dark["']/.test(selector) ? "dark" : "light";
      const hasDecls = /--[\w-]+\s*:/.test(match[2]);
      const hasThemeValue = Object.prototype.hasOwnProperty.call(values, theme);
      const value = hasThemeValue ? values[theme] : null;
      const already = new RegExp(`^\\s*${name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*:`, "m").test(match[2]);
      if (!hasDecls || !hasThemeValue || value == null || value === "" || (!already && appended[theme])) {
        next += match[0];
      } else {
        const patched = patchBlock(match[2], name, value);
        if (!already) appended[theme] = true;
        next += `${selector}{${patched.body}}`;
      }
      cursor = match.index + match[0].length;
    }
    next += css.slice(cursor);
    fs.writeFileSync(file, next);
    written.push(file);
  }
  return { status: "patched", programme, name, files: written };
}
