import fs from "node:fs";
import path from "node:path";
import { IDS_THEME_PATH, PROGRAMMES, REPO_ROOT } from "../paths.js";
import { readCatalog } from "../tokens/store.js";
import { validateCatalog } from "../validation/validate.js";

function cssValue(value) {
  return String(value).replace(/\s+/g, " ").trim();
}

export function renderIdsTheme(catalog) {
  const themes = catalog.themes ?? [];
  const tokens = catalog.tokens ?? [];
  const groups = [];
  for (const token of tokens) {
    const last = groups[groups.length - 1];
    if (!last || last.group !== token.group) groups.push({ group: token.group, tokens: [token] });
    else last.tokens.push(token);
  }
  const lightLines = [];
  for (const bucket of groups) {
    lightLines.push(`  /* --- ${bucket.group} --- */`);
    for (const token of bucket.tokens) {
      lightLines.push(`  ${token.name}: ${cssValue(token.values.light)};`);
    }
  }
  const extra = themes.filter((theme) => !theme.default);
  const extraBlocks = extra.map((theme) => {
    const lines = [];
    for (const token of tokens) {
      const own = token.values[theme.id];
      if (own == null || String(own).trim() === "" || own === token.values.light) continue;
      lines.push(`  ${token.name}: ${cssValue(own)};`);
    }
    return `html[data-design-system="ids"][data-theme="${theme.id}"], body[data-design-system="ids"][data-theme="${theme.id}"] {\n${lines.join("\n")}\n}`;
  });
  const source = catalog.source?.figmaLibrary ? `\n * Figma library: ${catalog.source.figmaLibrary}` : "";
  return `/*
 * IDS Design System — Global Theme Tokens
 * Generated by DTM from DTM/records/catalog.json.
 * Default theme: light. Other themes emit only values that differ from light.${source}
 * Scoped: html/body[data-design-system="ids"] (+ [data-theme]).
 */

html[data-design-system="ids"], body[data-design-system="ids"] {
${lightLines.join("\n")}
}

${extraBlocks.filter((block) => !block.endsWith("{\n}")).join("\n\n")}
`;
}

export function buildIdsTheme({ write = false } = {}) {
  const catalog = readCatalog();
  const validation = validateCatalog(catalog);
  if (!validation.ok) return { status: "rejected", errors: validation.errors };
  const css = renderIdsTheme(catalog);
  if (write) fs.writeFileSync(IDS_THEME_PATH, css);
  return { status: "built", css, path: write ? "components/ids-theme.css" : null };
}

function splitBlocks(css) {
  const blocks = [];
  const re = /([^{}@]+)\{([^{}]*)\}/g;
  let match;
  while ((match = re.exec(css))) {
    const selector = match[1].trim();
    const body = match[2];
    const decls = [];
    for (const line of body.split("\n")) {
      const prop = line.match(/^\s*(--[\w-]+)\s*:\s*([^;]+);/);
      if (prop) decls.push({ name: prop[1], value: prop[2].trim() });
    }
    if (!decls.length) continue;
    const theme = /data-theme\s*=\s*["']dark["']/.test(selector) ? "dark" : "light";
    blocks.push({ selector, theme, decls });
  }
  return blocks;
}

export function validateProgrammeFiles() {
  const catalog = readCatalog();
  const byName = new Map(catalog.tokens.map((token) => [token.name, token]));
  const reports = [];
  for (const [programme, config] of Object.entries(PROGRAMMES)) {
    for (const file of config.files) {
      if (!fs.existsSync(file)) continue;
      const css = fs.readFileSync(file, "utf8");
      const blocks = splitBlocks(css);
      const seen = new Set();
      const findings = [];
      for (const block of blocks) {
        for (const decl of block.decls) {
          seen.add(decl.name);
          const token = byName.get(decl.name);
          if (!token) {
            findings.push({ name: decl.name, status: "programme-local", theme: block.theme, value: decl.value });
            continue;
          }
          const expected = token.values[block.theme] ?? token.values.light;
          if (decl.value === expected) {
            findings.push({ name: decl.name, status: "in-sync", theme: block.theme, value: decl.value });
          } else {
            findings.push({
              name: decl.name,
              status: "override",
              theme: block.theme,
              value: decl.value,
              catalogValue: expected,
            });
          }
        }
      }
      let missing = 0;
      for (const token of catalog.tokens) {
        if (!seen.has(token.name)) missing += 1;
      }
      const counts = { "in-sync": 0, override: 0, "programme-local": 0, missing };
      for (const finding of findings) counts[finding.status] += 1;
      reports.push({
        programme,
        file: path.relative(REPO_ROOT, file),
        counts,
        findings,
      });
    }
  }
  return reports;
}

function patchBlock(body, name, value) {
  const line = new RegExp(`(^\\s*${name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*:\\s*)([^;]+)(;)`, "m");
  if (line.test(body)) return { body: body.replace(line, `$1${value}$3`), patched: true };
  const insertion = `\n  ${name}: ${value};`;
  return { body: `${body.replace(/\s*$/, "")}${insertion}\n`, patched: false, appended: true };
}

export function patchProgrammeToken(programme, name, values) {
  const config = PROGRAMMES[programme];
  if (!config) return { status: "rejected", errors: [{ field: "programme", message: "Unknown programme." }] };
  const catalog = readCatalog();
  const token = catalog.tokens.find((item) => item.name === name);
  if (!token) {
    return { status: "rejected", errors: [{ field: "name", message: "Name is not in the catalog. Add it as a common token first." }] };
  }
  const written = [];
  for (const file of config.files) {
    if (!fs.existsSync(file)) continue;
    const css = fs.readFileSync(file, "utf8");
    const re = /([^{}@]+)\{([^{}]*)\}/g;
    const matches = [...css.matchAll(re)];
    const appended = { light: false, dark: false };
    let next = "";
    let cursor = 0;
    for (const match of matches) {
      next += css.slice(cursor, match.index);
      const selector = match[1];
      const theme = /data-theme\s*=\s*["']dark["']/.test(selector) ? "dark" : "light";
      const hasDecls = /--[\w-]+\s*:/.test(match[2]);
      const hasThemeValue = Object.prototype.hasOwnProperty.call(values, theme);
      const value = hasThemeValue ? values[theme] : null;
      const already = new RegExp(`^\\s*${name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*:`, "m").test(match[2]);
      if (!hasDecls || !hasThemeValue || value == null || value === "" || (!already && appended[theme])) {
        next += match[0];
      } else {
        const patched = patchBlock(match[2], name, value);
        if (!already) appended[theme] = true;
        next += `${selector}{${patched.body}}`;
      }
      cursor = match.index + match[0].length;
    }
    next += css.slice(cursor);
    fs.writeFileSync(file, next);
    written.push(file);
  }
  return { status: "patched", programme, name, files: written };
}
