export {
  IdsGetStarted,
  IdsGetStartedCompound,
  GetStarted,
  IdsGetStartedHeroHeader,
  IdsGetStartedHeroBackground,
  IdsGetStartedHeroShadowBand,
  IdsGetStartedHeroHoneycomb,
  IdsGetStartedMastheadSlot,
  IdsGetStartedHeroTitle,
  IdsGetStartedHeroSubtitle,
  IdsGetStartedContainer,
  IdsGetStartedCardTrack,
  IdsGetStartedCardAnchor,
  IdsGetStartedCard,
  IdsGetStartedCardIconBadge,
  IdsGetStartedCardTitleBand,
  IdsGetStartedCardContentPanel,
  IdsGetStartedCardDescription,
  IdsGetStartedCardNote,
  IdsGetStartedCardConfigureButton,
  IdsGetStartedSkipButton,
  IdsGetStartedOverflowEdge,
  IdsGetStartedOverflowGradient,
  IdsGetStartedOverflowArrow,
  IdsGetStartedOverflowNavButton,
  type IdsGetStartedProps,
  type IdsGetStartedCardInput,
  type IdsGetStartedCardState,
  type IdsGetStartedOverflowPage,
  type IdsGetStartedOverflowSide,
  type IdsGetStartedMastheadProps,
  type IdsGetStartedHeroHeaderProps,
  type IdsGetStartedHeroBackgroundProps,
  type IdsGetStartedHeroShadowBandProps,
  type IdsGetStartedHeroHoneycombProps,
  type IdsGetStartedMastheadSlotProps,
  type IdsGetStartedHeroTitleProps,
  type IdsGetStartedHeroSubtitleProps,
  type IdsGetStartedContainerProps,
  type IdsGetStartedCardTrackProps,
  type IdsGetStartedCardAnchorProps,
  type IdsGetStartedCardProps,
  type IdsGetStartedCardIconBadgeProps,
  type IdsGetStartedCardTitleBandProps,
  type IdsGetStartedCardContentPanelProps,
  type IdsGetStartedCardDescriptionProps,
  type IdsGetStartedCardNoteProps,
  type IdsGetStartedCardConfigureButtonProps,
  type IdsGetStartedSkipButtonProps,
  type IdsGetStartedOverflowEdgeProps,
  type IdsGetStartedOverflowGradientProps,
  type IdsGetStartedOverflowArrowProps,
  type IdsGetStartedOverflowNavButtonProps,
} from "./IdsGetStarted";
export { default } from "./IdsGetStarted";
