/**
 * Synapse façade — strategy: reexport.
 * IDS implementation: `lib/react/ids/whats-new`.
 * Load `components/synapse-theme.css` only (not `ids-theme.css`).
 */
export {
  IdsWhatsNew as SynapseWhatsNew,
  IdsWhatsNewCompound as SynapseWhatsNewCompound,
  IdsWhatsNewHeader as SynapseWhatsNewHeader,
  IdsWhatsNewTitle as SynapseWhatsNewTitle,
  IdsWhatsNewCloseButton as SynapseWhatsNewCloseButton,
  IdsWhatsNewSummary as SynapseWhatsNewSummary,
  IdsWhatsNewBody as SynapseWhatsNewBody,
  IdsWhatsNewVersionFilterRow as SynapseWhatsNewVersionFilterRow,
  IdsWhatsNewVersion as SynapseWhatsNewVersion,
  IdsWhatsNewFilter as SynapseWhatsNewFilter,
  IdsWhatsNewSectionsScroll as SynapseWhatsNewSectionsScroll,
  IdsWhatsNewSection as SynapseWhatsNewSection,
  IdsWhatsNewThumbnail as SynapseWhatsNewThumbnail,
  IdsWhatsNewSectionHeader as SynapseWhatsNewSectionHeader,
  IdsWhatsNewBookmarkButton as SynapseWhatsNewBookmarkButton,
  IdsWhatsNewSectionTitle as SynapseWhatsNewSectionTitle,
  IdsWhatsNewDescription as SynapseWhatsNewDescription,
  IdsWhatsNewLink as SynapseWhatsNewLink,
  IdsWhatsNewShowMore as SynapseWhatsNewShowMore,
  IdsWhatsNewImages as SynapseWhatsNewImages,
  IdsWhatsNewImage as SynapseWhatsNewImage,
  IdsWhatsNewFooter as SynapseWhatsNewFooter,
  type IdsWhatsNewProps as SynapseWhatsNewProps,
  type WhatsNewFilter as SynapseWhatsNewFilterKind,
  type IdsWhatsNewLayer as SynapseWhatsNewLayer,
  type IdsWhatsNewSectionInput as SynapseWhatsNewSectionInput,
  type IdsWhatsNewSectionImage as SynapseWhatsNewSectionImage,
  type IdsWhatsNewTitleProps as SynapseWhatsNewTitleProps,
  type IdsWhatsNewCloseButtonProps as SynapseWhatsNewCloseButtonProps,
  type IdsWhatsNewHeaderProps as SynapseWhatsNewHeaderProps,
  type IdsWhatsNewSummaryProps as SynapseWhatsNewSummaryProps,
  type IdsWhatsNewVersionProps as SynapseWhatsNewVersionProps,
  type IdsWhatsNewFilterProps as SynapseWhatsNewFilterProps,
  type IdsWhatsNewVersionFilterRowProps as SynapseWhatsNewVersionFilterRowProps,
  type IdsWhatsNewSectionsScrollProps as SynapseWhatsNewSectionsScrollProps,
  type IdsWhatsNewBodyProps as SynapseWhatsNewBodyProps,
  type IdsWhatsNewThumbnailProps as SynapseWhatsNewThumbnailProps,
  type IdsWhatsNewBookmarkButtonProps as SynapseWhatsNewBookmarkButtonProps,
  type IdsWhatsNewSectionTitleProps as SynapseWhatsNewSectionTitleProps,
  type IdsWhatsNewSectionHeaderProps as SynapseWhatsNewSectionHeaderProps,
  type IdsWhatsNewLinkProps as SynapseWhatsNewLinkProps,
  type IdsWhatsNewShowMoreProps as SynapseWhatsNewShowMoreProps,
  type IdsWhatsNewDescriptionProps as SynapseWhatsNewDescriptionProps,
  type IdsWhatsNewImageProps as SynapseWhatsNewImageProps,
  type IdsWhatsNewImagesProps as SynapseWhatsNewImagesProps,
  type IdsWhatsNewSectionProps as SynapseWhatsNewSectionProps,
  type IdsWhatsNewFooterProps as SynapseWhatsNewFooterProps,
} from "../../ids/whats-new";
