export {
  IdsWhatsNew,
  IdsWhatsNewCompound,
  WhatsNew,
  IdsWhatsNewHeader,
  IdsWhatsNewTitle,
  IdsWhatsNewCloseButton,
  IdsWhatsNewSummary,
  IdsWhatsNewBody,
  IdsWhatsNewVersionFilterRow,
  IdsWhatsNewVersion,
  IdsWhatsNewFilter,
  IdsWhatsNewSectionsScroll,
  IdsWhatsNewSection,
  IdsWhatsNewThumbnail,
  IdsWhatsNewSectionHeader,
  IdsWhatsNewBookmarkButton,
  IdsWhatsNewSectionTitle,
  IdsWhatsNewDescription,
  IdsWhatsNewLink,
  IdsWhatsNewShowMore,
  IdsWhatsNewImages,
  IdsWhatsNewImage,
  IdsWhatsNewFooter,
  type IdsWhatsNewProps,
  type WhatsNewFilter,
  type IdsWhatsNewLayer,
  type IdsWhatsNewSectionInput,
  type IdsWhatsNewSectionImage,
  type IdsWhatsNewTitleProps,
  type IdsWhatsNewCloseButtonProps,
  type IdsWhatsNewHeaderProps,
  type IdsWhatsNewSummaryProps,
  type IdsWhatsNewVersionProps,
  type IdsWhatsNewFilterProps,
  type IdsWhatsNewVersionFilterRowProps,
  type IdsWhatsNewSectionsScrollProps,
  type IdsWhatsNewBodyProps,
  type IdsWhatsNewThumbnailProps,
  type IdsWhatsNewBookmarkButtonProps,
  type IdsWhatsNewSectionTitleProps,
  type IdsWhatsNewSectionHeaderProps,
  type IdsWhatsNewLinkProps,
  type IdsWhatsNewShowMoreProps,
  type IdsWhatsNewDescriptionProps,
  type IdsWhatsNewImageProps,
  type IdsWhatsNewImagesProps,
  type IdsWhatsNewSectionProps,
  type IdsWhatsNewFooterProps,
} from "./IdsWhatsNew";
export { default } from "./IdsWhatsNew";
