"""Background execution of pending jobs against Cursor Cloud."""

from __future__ import annotations

import logging
import threading
from typing import TYPE_CHECKING

from ..models.jobs import JobStatus
from .agent_runner import clear_cancel_state, is_cancel_requested, run_cloud_agent
from .secrets import redact_text

if TYPE_CHECKING:
    from .audit import AuditLog
    from .job_store import JobStore

logger = logging.getLogger(__name__)

_lock = threading.Lock()
_running: set[str] = set()


def start_job_in_background(
    store: JobStore,
    job_id: str,
    *,
    audit: AuditLog | None = None,
    actor: str = "anonymous",
) -> bool:
    """Spawn a daemon thread to run the cloud agent. Returns False if already running."""
    with _lock:
        if job_id in _running:
            return False
        _running.add(job_id)

    thread = threading.Thread(
        target=_execute,
        args=(store, job_id, audit, actor),
        name=f"cloud-agent-{job_id[:8]}",
        daemon=True,
    )
    thread.start()
    return True


def is_job_thread_running(job_id: str) -> bool:
    with _lock:
        return job_id in _running


def _execute(
    store: JobStore,
    job_id: str,
    audit: AuditLog | None,
    actor: str,
) -> None:
    try:
        record = store.get(job_id)
        if record is None:
            logger.error("Job %s not found for agent run", job_id)
            return

        if record.cancel_requested or is_cancel_requested(job_id):
            record.status = JobStatus.cancelled
            record.error_message = "Cancelled before agent start"
            store.save(record)
            if audit:
                audit.write(
                    "agent_cancelled",
                    job_id=job_id,
                    actor=actor,
                    detail={"phase": "before_start"},
                )
            return

        prompt = (record.prompt_package or {}).get("prompt_text") or ""
        if not prompt.strip():
            record.status = JobStatus.error
            record.error_message = "Job has empty prompt_text"
            store.save(record)
            return

        record.status = JobStatus.running
        record.error_message = None
        store.save(record)
        if audit:
            audit.write(
                "agent_started",
                job_id=job_id,
                actor=actor,
                detail={"lockedRepoUrl": record.locked_repo_url},
            )

        outcome = run_cloud_agent(prompt, job_id=job_id)
        record = store.get(job_id) or record
        record.agent_id = outcome.agent_id
        record.run_id = outcome.run_id
        record.result_summary = outcome.result_summary
        record.locked_repo_url = outcome.locked_repo_url or record.locked_repo_url
        record.branch = outcome.branch
        record.pr_url = outcome.pr_url
        record.ide_checkout_hint = outcome.ide_checkout_hint

        # Phase 4: if branch exists but no PR, try GitHub API (when not dry-run)
        if (
            outcome.status == "finished"
            and record.branch
            and not record.pr_url
            and not outcome.dry_run
        ):
            try:
                from ..config import settings
                from .github_api import ensure_pr_for_branch, parse_github_repo

                if settings.cloud_auto_create_pr or settings.github_token:
                    gh = parse_github_repo(record.locked_repo_url)
                    if gh and settings.github_token:
                        slug = (record.preview or {}).get("slug") or "component"
                        programme = (record.preview or {}).get("programme") or ""
                        pr = ensure_pr_for_branch(
                            gh,
                            record.branch,
                            title=f"design-spec: {programme}/{slug}",
                            body=(
                                f"Generated by Design Spec Portal job `{job_id}`.\n\n"
                                f"- Branch: `{record.branch}`\n"
                                f"- Spec: `{(record.preview or {}).get('design_spec_path')}`\n"
                            ),
                        )
                        if pr:
                            record.pr_url = pr
                            if record.ide_checkout_hint and pr not in record.ide_checkout_hint:
                                record.ide_checkout_hint += f"\n# PR: {pr}"
            except Exception as exc:  # noqa: BLE001
                logger.warning("PR ensure failed for %s: %s", job_id, exc)

        if outcome.status == "finished":
            record.status = JobStatus.finished
            record.error_message = None
            if audit:
                audit.write(
                    "agent_finished",
                    job_id=job_id,
                    actor=actor,
                    detail={
                        "agentId": outcome.agent_id,
                        "runId": outcome.run_id,
                        "branch": record.branch,
                        "prUrl": record.pr_url,
                    },
                )
        elif outcome.status == "cancelled":
            record.status = JobStatus.cancelled
            record.cancel_requested = True
            record.error_message = outcome.error_message or "Cancelled"
            if audit:
                audit.write(
                    "agent_cancelled",
                    job_id=job_id,
                    actor=actor,
                    detail={
                        "agentId": outcome.agent_id,
                        "runId": outcome.run_id,
                        "branch": outcome.branch,
                    },
                )
        else:
            record.status = JobStatus.error
            record.error_message = redact_text(
                outcome.error_message or "Agent run failed"
            )
            if audit:
                audit.write(
                    "agent_error",
                    job_id=job_id,
                    actor=actor,
                    detail={
                        "startupFailure": outcome.startup_failure,
                        "error": record.error_message,
                        "branch": outcome.branch,
                    },
                )
        store.save(record)
        logger.info(
            "Job %s → %s agent_id=%s run_id=%s",
            job_id,
            record.status.value,
            record.agent_id,
            record.run_id,
        )
    except Exception:  # noqa: BLE001
        logger.exception("Background agent thread crashed for %s", job_id)
        record = store.get(job_id)
        if record is not None:
            record.status = JobStatus.error
            record.error_message = "Background agent thread crashed — see server logs"
            store.save(record)
            if audit:
                audit.write(
                    "agent_error",
                    job_id=job_id,
                    actor=actor,
                    detail={"error": record.error_message},
                )
    finally:
        clear_cancel_state(job_id)
        with _lock:
            _running.discard(job_id)
