import { IdsWizardComponent } from "./ids-wizard.component";
import {
  IdsWizardBodyComponent,
  IdsWizardCancelButtonComponent,
  IdsWizardCloseActionComponent,
  IdsWizardContentPaneComponent,
  IdsWizardFooterActionsComponent,
  IdsWizardFooterComponent,
  IdsWizardHeaderComponent,
  IdsWizardHeaderTitleComponent,
  IdsWizardPageContentComponent,
  IdsWizardPageTitleComponent,
  IdsWizardPreviousButtonComponent,
  IdsWizardPrimaryButtonComponent,
  IdsWizardProgressLabelComponent,
  IdsWizardStepItemComponent,
  IdsWizardStepLabelComponent,
  IdsWizardStepStatusIndicatorComponent,
  IdsWizardStepsPaneComponent,
  IdsWizardSubstepItemComponent,
  IdsWizardSubstepListComponent,
} from "./ids-wizard-slots.component";
import { IdsIconComponent } from "../icon/ids-icon.component";
import { IdsButtonComponent } from "../button/ids-button.component";

export const IDS_WIZARD_IMPORTS = [
  IdsWizardComponent,
  IdsWizardHeaderComponent,
  IdsWizardHeaderTitleComponent,
  IdsWizardCloseActionComponent,
  IdsWizardBodyComponent,
  IdsWizardStepsPaneComponent,
  IdsWizardStepItemComponent,
  IdsWizardStepLabelComponent,
  IdsWizardStepStatusIndicatorComponent,
  IdsWizardSubstepListComponent,
  IdsWizardSubstepItemComponent,
  IdsWizardContentPaneComponent,
  IdsWizardPageTitleComponent,
  IdsWizardPageContentComponent,
  IdsWizardFooterComponent,
  IdsWizardProgressLabelComponent,
  IdsWizardFooterActionsComponent,
  IdsWizardCancelButtonComponent,
  IdsWizardPreviousButtonComponent,
  IdsWizardPrimaryButtonComponent,
  IdsIconComponent,
  IdsButtonComponent,
] as const;

export {
  IdsWizardComponent,
  IdsWizardHeaderComponent,
  IdsWizardHeaderTitleComponent,
  IdsWizardCloseActionComponent,
  IdsWizardBodyComponent,
  IdsWizardStepsPaneComponent,
  IdsWizardStepItemComponent,
  IdsWizardStepLabelComponent,
  IdsWizardStepStatusIndicatorComponent,
  IdsWizardSubstepListComponent,
  IdsWizardSubstepItemComponent,
  IdsWizardContentPaneComponent,
  IdsWizardPageTitleComponent,
  IdsWizardPageContentComponent,
  IdsWizardFooterComponent,
  IdsWizardProgressLabelComponent,
  IdsWizardFooterActionsComponent,
  IdsWizardCancelButtonComponent,
  IdsWizardPreviousButtonComponent,
  IdsWizardPrimaryButtonComponent,
};

export type {
  IdsWizardContext,
  IdsWizardEventPayload,
  IdsWizardFooterButtons,
  IdsWizardMode,
  IdsWizardSize,
  IdsWizardStepContent,
  IdsWizardStepInput,
  IdsWizardStepStatus,
} from "./ids-wizard.types";
