/**
 * Builds `.design-sync/synapse-theme-bundle.css` — the single stylesheet design-sync appends
 * into the shipped Synapse bundle via `cfg.cssEntry`.
 *
 * Mirrors `scripts/build_ids_sync_theme.mjs`. Three jobs:
 *
 * 1. ADD `:root` TO THE PROGRAMME ALIASES. Most Synapse tokens are already declared at a bare
 *    `:root` (unlike IDS), but ~25 *programme layout aliases* — every control radius, the button
 *    focus ring, the chat-input shell metrics — live under
 *    `html[data-design-system="synapse"], body[data-design-system="synapse"]`.
 *    Storybook sets that attribute from a decorator; a design built on claude.ai/design does NOT
 *    (its page shell is out of the component author's control), so without this hoist every
 *    `border-radius: var(--button-control-radius)` and friend silently drops and the whole system
 *    renders with square corners and no focus rings. The synced bundle contains only Synapse, so
 *    making Synapse the unconditional default is safe here. Dark mode still needs
 *    `[data-theme="dark"]`.
 *
 * 2. DROP THE REMOTE FONT `@import`. `synapse-theme.css` pulls Roboto from Google Fonts. A CSS
 *    `@import` is only honoured at the TOP of a stylesheet, and design-sync APPENDS `cssEntry`
 *    into the bundle CSS — so the rule would be silently ignored, leaving `[FONT_MISSING]` and a
 *    chromium-default serif in every design. Roboto ships instead as a local variable font via
 *    `cfg.extraFonts` (`assets/fonts/roboto/roboto-variable-latin.woff2`), which also keeps
 *    designs independent of a font CDN.
 *
 * 3. CONCATENATE the optional hand-maintained `components/synapse-theme-fallbacks.css` when it
 *    exists (`cssEntry` accepts exactly one file).
 *
 * This output is a build artifact: regenerate it, never hand-edit it.
 *   node scripts/build_synapse_sync_theme.mjs
 */
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(repoRoot, ".design-sync/synapse-theme-bundle.css");

const LIGHT_SEL = 'html[data-design-system="synapse"],\nbody[data-design-system="synapse"]';
const LIGHT_SEL_ROOTED = `:root,\n${LIGHT_SEL}`;

/** Hoist the programme-alias selector to also match a bare `:root`. */
function addRoot(css) {
  if (!css.includes(LIGHT_SEL)) {
    throw new Error(`expected selector not found — theme structure changed: ${LIGHT_SEL}`);
  }
  return css.split(LIGHT_SEL).join(LIGHT_SEL_ROOTED);
}

/** Remove @import rules; they cannot survive being appended into the bundle CSS. */
const dropped = [];
function dropImports(css) {
  return css.replace(/^[ \t]*@import[^\n]*;[ \t]*$/gm, (m) => {
    dropped.push(m.trim());
    return "/* @import dropped by build_synapse_sync_theme.mjs — see cfg.extraFonts */";
  });
}

let css = addRoot(dropImports(readFileSync(join(repoRoot, "components/synapse-theme.css"), "utf8")));

const fallbacksPath = join(repoRoot, "components/synapse-theme-fallbacks.css");
if (existsSync(fallbacksPath)) {
  css += "\n" + dropImports(readFileSync(fallbacksPath, "utf8"));
}

const banner = `/* GENERATED by scripts/build_synapse_sync_theme.mjs — do not edit.
 * components/synapse-theme.css${existsSync(fallbacksPath) ? " + components/synapse-theme-fallbacks.css" : ""}, with the
 * programme layout aliases also bound to :root so designs render without needing
 * data-design-system="synapse" on the host page. Remote font @imports removed (see cfg.extraFonts). */\n`;

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, banner + "\n" + css);
console.log(
  `wrote ${out} — ${(readFileSync(out, "utf8").length / 1024).toFixed(0)} KB, ` +
    `${dropped.length} @import(s) dropped${existsSync(fallbacksPath) ? ", fallbacks included" : ""}`,
);
