/**
 * Builds `.design-sync/ids-theme-bundle.css` — the single stylesheet design-sync appends
 * into the shipped bundle via `cfg.cssEntry`.
 *
 * Two jobs:
 *
 * 1. CONCATENATE. `cssEntry` accepts exactly one file, but IDS needs both the generated
 *    `components/ids-theme.css` and the hand-maintained `components/ids-theme-fallbacks.css`.
 *
 * 2. ADD `:root`. Both source files scope their tokens to `html[data-design-system="ids"]`.
 *    Storybook has a decorator that sets that attribute; a design built on claude.ai/design
 *    does NOT — its page shell is out of the component author's control — so without this the
 *    entire design system would render unstyled. The synced bundle contains only IDS, so making
 *    IDS the unconditional default is safe here. Dark mode still requires `[data-theme="dark"]`.
 *
 * This output is a build artifact: regenerate it, never hand-edit it.
 *   node scripts/build_ids_sync_theme.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(repoRoot, ".design-sync/ids-theme-bundle.css");

const LIGHT_SEL = 'html[data-design-system="ids"], body[data-design-system="ids"]';
const LIGHT_SEL_ROOTED = `:root, ${LIGHT_SEL}`;

/** Hoist a light-theme selector to also match a bare `:root`. */
function addRoot(css) {
  if (!css.includes(LIGHT_SEL)) {
    throw new Error(`expected selector not found — theme structure changed: ${LIGHT_SEL}`);
  }
  return css.split(LIGHT_SEL).join(LIGHT_SEL_ROOTED);
}

// @import must precede every other rule in a stylesheet, so hoist them to the top.
// NB: match to end-of-line, not to the first `;` — Google Fonts URLs contain
// semicolons in the weight list (`wght@300;400;500;700`).
const imports = [];
function hoistImports(css) {
  return css.replace(/^[ \t]*@import[^\n]*;[ \t]*$/gm, (m) => {
    imports.push(m.trim());
    return "";
  });
}

const theme = hoistImports(readFileSync(join(repoRoot, "components/ids-theme.css"), "utf8"));
const fallbacks = hoistImports(readFileSync(join(repoRoot, "components/ids-theme-fallbacks.css"), "utf8"));

const banner = `/* GENERATED by scripts/build_ids_sync_theme.mjs — do not edit.
 * ids-theme.css + ids-theme-fallbacks.css, with light-theme tokens also bound to :root
 * so designs render without needing data-design-system="ids" on the host page. */\n`;

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, [banner, ...[...new Set(imports)], addRoot(theme), addRoot(fallbacks)].join("\n"));
console.log(`wrote ${out} — ${(readFileSync(out, "utf8").length / 1024).toFixed(0)} KB, ${imports.length} hoisted @import(s)`);
