/**
 * Synapse façade — strategy: reexport.
 * IDS implementation: `lib/react/ids/wizard`.
 * Load `components/synapse-theme.css` only (not `ids-theme.css`).
 */
export {
  IdsWizard as SynapseWizard,
  IdsWizardCompound as SynapseWizardCompound,
  IdsWizardHeader as SynapseWizardHeader,
  IdsWizardHeaderTitle as SynapseWizardHeaderTitle,
  IdsWizardCloseAction as SynapseWizardCloseAction,
  IdsWizardBody as SynapseWizardBody,
  IdsWizardStepsPane as SynapseWizardStepsPane,
  IdsWizardStepItem as SynapseWizardStepItem,
  IdsWizardStepLabel as SynapseWizardStepLabel,
  IdsWizardStepStatusIndicator as SynapseWizardStepStatusIndicator,
  IdsWizardSubstepList as SynapseWizardSubstepList,
  IdsWizardSubstepItem as SynapseWizardSubstepItem,
  IdsWizardContentPane as SynapseWizardContentPane,
  IdsWizardPageTitle as SynapseWizardPageTitle,
  IdsWizardPageContent as SynapseWizardPageContent,
  IdsWizardFooter as SynapseWizardFooter,
  IdsWizardProgressLabel as SynapseWizardProgressLabel,
  IdsWizardFooterActions as SynapseWizardFooterActions,
  IdsWizardCancelButton as SynapseWizardCancelButton,
  IdsWizardPreviousButton as SynapseWizardPreviousButton,
  IdsWizardPrimaryButton as SynapseWizardPrimaryButton,
  type IdsWizardProps as SynapseWizardProps,
  type IdsWizardMode as SynapseWizardMode,
  type IdsWizardSize as SynapseWizardSize,
  type IdsWizardStepStatus as SynapseWizardStepStatus,
  type IdsWizardContext as SynapseWizardContext,
  type IdsWizardFooterButtons as SynapseWizardFooterButtons,
  type IdsWizardStepInput as SynapseWizardStepInput,
  type IdsWizardEventPayload as SynapseWizardEventPayload,
  type IdsWizardHeaderProps as SynapseWizardHeaderProps,
  type IdsWizardHeaderTitleProps as SynapseWizardHeaderTitleProps,
  type IdsWizardCloseActionProps as SynapseWizardCloseActionProps,
  type IdsWizardBodyProps as SynapseWizardBodyProps,
  type IdsWizardStepsPaneProps as SynapseWizardStepsPaneProps,
  type IdsWizardStepItemProps as SynapseWizardStepItemProps,
  type IdsWizardStepLabelProps as SynapseWizardStepLabelProps,
  type IdsWizardStepStatusIndicatorProps as SynapseWizardStepStatusIndicatorProps,
  type IdsWizardSubstepListProps as SynapseWizardSubstepListProps,
  type IdsWizardSubstepItemProps as SynapseWizardSubstepItemProps,
  type IdsWizardContentPaneProps as SynapseWizardContentPaneProps,
  type IdsWizardPageTitleProps as SynapseWizardPageTitleProps,
  type IdsWizardPageContentProps as SynapseWizardPageContentProps,
  type IdsWizardFooterProps as SynapseWizardFooterProps,
  type IdsWizardProgressLabelProps as SynapseWizardProgressLabelProps,
  type IdsWizardFooterActionsProps as SynapseWizardFooterActionsProps,
  type IdsWizardCancelButtonProps as SynapseWizardCancelButtonProps,
  type IdsWizardPreviousButtonProps as SynapseWizardPreviousButtonProps,
  type IdsWizardPrimaryButtonProps as SynapseWizardPrimaryButtonProps,
} from "../../ids/wizard";
