/* @generated by strict-spec-storybook-gate */
/* component: badge */
/* spec_hash: da57ab72f3e3d8193d66a61f758dbe83341fa0d6f861e5ae6c5eea0e80d1ec43 */
import React from "react";
import "../../../../components/ids-theme.css";
import type { Meta, StoryObj } from "@storybook/react";
import { IdsBadge as IdsBadge } from "../../../../storybook/src/components/IdsBadge";

const meta: Meta<typeof IdsBadge> = {
  title: "Spec Generated/IDS/Badge",
  component: IdsBadge,
  parameters: { layout: "centered" },
  args: {
    value: 8,
    type: "default",
  },
  argTypes: {
    value: { control: "text" },
    type: {
      control: "select",
      options: ["default", "critical", "warning", "disabled", "success"],
    },
    ariaLabel: { control: "text" },
  },
};

export default meta;
type Story = StoryObj<typeof IdsBadge>;

export const Playground: Story = {
  render: (args) => <IdsBadge {...args} />,
};

export const Types: Story = {
  render: () => (
    <div className="sbBadgeRow">
      <IdsBadge value={1} type="default" />
      <IdsBadge value={4} type="critical" />
      <IdsBadge value={12} type="warning" />
      <IdsBadge value={7} type="disabled" />
      <IdsBadge value={99} type="success" />
    </div>
  ),
};

export const ContentSizing: Story = {
  render: () => (
    <div className="sbBadgeRow">
      <IdsBadge value={1} type="default" />
      <IdsBadge value={12} type="default" />
      <IdsBadge value={128} type="default" />
      <IdsBadge value={"999+"} type="default" ariaLabel="Nine hundred ninety nine plus notifications" />
    </div>
  ),
};

export const BackgroundShowcase: Story = {
  render: () => (
    <div className="sbBadgeCol">
      <div className="sbBadgeSurfaceBlue">
        <IdsBadge value={3} type="default" />
        <IdsBadge value={8} type="critical" />
        <IdsBadge value={12} type="warning" />
      </div>
      <div className="sbBadgeSurfaceGray">
        <IdsBadge value={3} type="default" />
        <IdsBadge value={8} type="critical" />
        <IdsBadge value={12} type="warning" />
      </div>
    </div>
  ),
};

export const LayoutTokens: Story = {
  render: () => (
    <style>{
      `
      .sbBadgeRow {
        display: flex;
        gap: 12px;
        align-items: center;
        flex-wrap: wrap;
      }
      .sbBadgeCol {
        display: grid;
        gap: 12px;
      }
      .sbBadgeSurfaceBlue {
        display: flex;
        gap: 12px;
        align-items: center;
        flex-wrap: wrap;
        padding: 12px;
        border-radius: 6px;
        background: var(--color-background-brand-base);
      }
      .sbBadgeSurfaceGray {
        display: flex;
        gap: 12px;
        align-items: center;
        flex-wrap: wrap;
        padding: 12px;
        border-radius: 6px;
        background: var(--color-background-gray-subtle);
        border: 1px solid var(--color-border-subtle);
        --ids-badge-warning-border-color: var(--color-border-alerting-minor-base);
      }
      `
    }</style>
  ),
};
