/* @generated by strict-spec-storybook-gate */
/* component: checkbox */
/* spec_hash: f15de0b974a92c1f70f5fe77b13d98f95199f294fc3ce416f49bd33070d9d2a4 */
import React from "react";
import "../../../../components/ids-theme.css";
import type { Meta, StoryObj } from "@storybook/react";
import { useState } from "react";
import { Checkbox as IdsCheckbox } from "../../../../storybook/src/components/Checkbox";

const HARNESS_OPTION_LABEL = "Option";

const sharedCheckboxStoryStyles = `
  .sbCheckboxRow {
    display: flex;
    gap: 16px;
    flex-wrap: wrap;
    align-items: flex-start;
  }
  .sbCheckboxCol {
    display: grid;
    gap: 20px;
  }
  .sbHarness {
    display: grid;
    grid-template-columns: 118px repeat(5, minmax(132px, max-content));
    gap: 16px 22px;
    align-items: start;
  }
  .sbHarnessLegend {
    grid-column: 1 / -1;
    font-size: 13px;
    line-height: 1.45;
    margin: 0 0 10px;
    max-width: 800px;
  }
  .sbHarnessCorner {
    min-height: 4px;
  }
  .sbHarnessHeader {
    font-size: 10px;
    font-weight: 600;
    letter-spacing: 0.05em;
    text-transform: uppercase;
    opacity: 0.72;
    padding-bottom: 6px;
    border-bottom: 1px solid var(--color-border-accessible, #757575);
  }
  .sbHarnessTitle {
    font-size: 12px;
    font-weight: 600;
    opacity: 0.85;
    padding-top: 6px;
  }
  .sbHarnessControl {
    display: flex;
    flex-direction: column;
    gap: 6px;
    justify-content: flex-start;
    min-height: 40px;
  }
  .sbHarnessHint {
    font-size: 10px;
    line-height: 1.25;
    opacity: 0.62;
    max-width: 152px;
  }
`;

const meta: Meta<typeof IdsCheckbox> = {
  title: "Spec Generated/IDS/Checkbox",
  component: IdsCheckbox,
  parameters: { layout: "padded" },
  decorators: [
    (Story) => (
      <>
        <style>{sharedCheckboxStoryStyles}</style>
        <Story />
      </>
    ),
  ],
  argTypes: {
    disabled: { control: "boolean" },
    indeterminate: { control: "boolean" },
    error: { control: "boolean" },
    helperText: { control: "text" },
    label: { control: "text" },
  },
  args: {
    label: "Accept terms and conditions",
    disabled: false,
    indeterminate: false,
    error: false,
  },
};

export default meta;
type Story = StoryObj<typeof IdsCheckbox>;

export const Playground: Story = {
  args: {
    showLabel: true
  },

  render: (args) => <IdsCheckbox {...args} />
};

export const SelectionStates: Story = {
  render: () => (
    <div className="sbCheckboxRow">
      <IdsCheckbox label="Unchecked" />
      <IdsCheckbox label="Checked" checked />
      <IdsCheckbox label="Partial" indeterminate />
    </div>
  ),
};

export const DisabledStates: Story = {
  render: () => (
    <div className="sbCheckboxRow">
      <IdsCheckbox label="Unchecked" disabled />
      <IdsCheckbox label="Checked" checked disabled />
      <IdsCheckbox label="Indeterminate" indeterminate disabled />
    </div>
  ),
};

export const ValidationAndHelperText: Story = {
  render: () => (
    <div className="sbCheckboxCol">
      <IdsCheckbox label="Email notifications" helperText="Receive weekly summary updates." />
      <IdsCheckbox
        label="Required acknowledgement"
        error
        helperText="You must accept this option to continue."
      />
      <IdsCheckbox label="Disabled option" disabled helperText="This option is unavailable for your role." />
      <IdsCheckbox
        label="Checked with validation error"
        checked
        error
        helperText="Error message only — control keeps selected styling."
      />
    </div>
  ),
};

export const ControlledExample: Story = {
  render: () => {
    const [checked, setChecked] = useState(false);
    return (
      <div className="sbCheckboxCol">
        <IdsCheckbox
          label="Controlled checkbox"
          checked={checked}
          helperText={`Current value: ${checked ? "checked" : "unchecked"}`}
          onChange={setChecked}
        />
      </div>
    );
  },
};

export const StateHarness: Story = {
  render: () => (
    <div className="sbHarness">
      <div className="sbHarnessLegend">
        Rows: Unchecked, Checked, Partial. Columns: Default, Hover (pointer over the box), Focus (
        <code>simulateFocusVisible</code>
        ), Disabled, Error.
      </div>

      <div className="sbHarnessCorner" />
      <div className="sbHarnessHeader">Default</div>
      <div className="sbHarnessHeader">Hover</div>
      <div className="sbHarnessHeader">Focus</div>
      <div className="sbHarnessHeader">Disabled</div>
      <div className="sbHarnessHeader">Error</div>

      <div className="sbHarnessTitle">Unchecked</div>
      <div className="sbHarnessControl">
        <IdsCheckbox label={HARNESS_OPTION_LABEL} />
      </div>
      <div className="sbHarnessControl">
        <IdsCheckbox label={HARNESS_OPTION_LABEL} />
        <span className="sbHarnessHint">Hover the control for strong border.</span>
      </div>
      <div className="sbHarnessControl">
        <IdsCheckbox label={HARNESS_OPTION_LABEL} simulateFocusVisible />
      </div>
      <div className="sbHarnessControl">
        <IdsCheckbox label={HARNESS_OPTION_LABEL} disabled />
      </div>
      <div className="sbHarnessControl">
        <IdsCheckbox label={HARNESS_OPTION_LABEL} error helperText="Error message" />
      </div>

      <div className="sbHarnessTitle">Checked</div>
      <div className="sbHarnessControl">
        <IdsCheckbox label={HARNESS_OPTION_LABEL} checked />
      </div>
      <div className="sbHarnessControl">
        <IdsCheckbox label={HARNESS_OPTION_LABEL} checked />
        <span className="sbHarnessHint">Hover for brand-strong fill.</span>
      </div>
      <div className="sbHarnessControl">
        <IdsCheckbox label={HARNESS_OPTION_LABEL} checked simulateFocusVisible />
      </div>
      <div className="sbHarnessControl">
        <IdsCheckbox label={HARNESS_OPTION_LABEL} checked disabled />
      </div>
      <div className="sbHarnessControl">
        <IdsCheckbox label={HARNESS_OPTION_LABEL} checked error helperText="Error message" />
      </div>

      <div className="sbHarnessTitle">Partial</div>
      <div className="sbHarnessControl">
        <IdsCheckbox label={HARNESS_OPTION_LABEL} indeterminate />
      </div>
      <div className="sbHarnessControl">
        <IdsCheckbox label={HARNESS_OPTION_LABEL} indeterminate />
        <span className="sbHarnessHint">Hover for strong border; dash stays brand.</span>
      </div>
      <div className="sbHarnessControl">
        <IdsCheckbox label={HARNESS_OPTION_LABEL} indeterminate simulateFocusVisible />
      </div>
      <div className="sbHarnessControl">
        <IdsCheckbox label={HARNESS_OPTION_LABEL} indeterminate disabled />
      </div>
      <div className="sbHarnessControl">
        <IdsCheckbox label={HARNESS_OPTION_LABEL} indeterminate error helperText="Error message" />
      </div>
    </div>
  ),
};

export const LayoutTokens: Story = {
  render: () => (
    <div className="sbCheckboxCol" style={{ maxWidth: 520 }}>
      <p style={{ fontSize: 13, margin: 0, lineHeight: 1.5 }}>
        Spacing helpers are injected via <code>meta.decorators</code> (<code>.sbCheckboxRow</code>,{" "}
        <code>.sbHarness</code>, etc.).
      </p>
      <div className="sbCheckboxRow">
        <IdsCheckbox label="Sample A" />
        <IdsCheckbox label="Sample B" checked />
      </div>
    </div>
  ),
};
