/* @generated by strict-spec-storybook-gate */
/* component: datagrid */
/* spec_hash: 3c60fd519a2b1a754a0d1080ff7248d5ef983a237f265d52f0de3a0c3600996c */
import "../../../../components/ids-theme.css";
import type { Meta, StoryObj } from "@storybook/react";
import React, { type ComponentProps } from "react";
import {
  IdsDataGrid,
  IdsDataGridFilterSearchField,
  type IdsDataGridColumn,
} from "../../../../storybook/src/components/IdsDataGrid";
import { IdsDataGridDefaultStoryHost } from "../../../../storybook/src/components/IdsDataGridDefaultStoryHost";
import { IdsDataGridDateAndTimeFilterStoryHost } from "../../../../storybook/src/components/IdsDataGridDateAndTimeFilterStoryHost";
import { IdsDataGridDateFilterStoryHost } from "../../../../storybook/src/components/IdsDataGridDateFilterStoryHost";
import { IdsDataGridNumericFilterStoryHost } from "../../../../storybook/src/components/IdsDataGridNumericFilterStoryHost";

const DESIGN_SPEC_PATH = "components/ids/datagrid/design-spec.md";

/** Columns aligned to spec anatomy: sort (`col-sort-*-16`), filter (L-frame + `filterPanel`), settings column is grid-owned. */
const specColumns: IdsDataGridColumn[] = [
  {
    key: "name",
    title: "Name",
    sortable: true,
    filterable: true,
    minWidth: 90,
    width: 200,
    filterPanel: <IdsDataGridFilterSearchField aria-label="Search name column" />,
  },
  {
    key: "type",
    title: "Type",
    sortable: true,
    filterable: true,
    columnHideable: true,
    minWidth: 90,
    width: 140,
  },
  {
    key: "status",
    title: "Status",
    sortable: true,
    filterable: true,
    columnHideable: true,
    minWidth: 90,
    width: 120,
  },
  {
    key: "amount",
    title: "Amount",
    sortable: true,
    filterable: true,
    columnHideable: true,
    minWidth: 90,
    width: 120,
  },
  {
    key: "dueDate",
    title: "Due Date",
    sortable: true,
    filterable: true,
    columnHideable: true,
    minWidth: 120,
    width: 160,
  },
  {
    key: "updatedAt",
    title: "Updated",
    sortable: true,
    filterable: true,
    columnHideable: true,
    minWidth: 120,
    width: 180,
  },
  {
    key: "owner",
    title: "Owner",
    sortable: true,
    filterable: true,
    columnHideable: true,
    minWidth: 90,
    width: 120,
  },
  {
    key: "region",
    title: "Region",
    sortable: false,
    filterable: true,
    columnHideable: true,
    minWidth: 90,
    width: 100,
  },
];

const DEMO_UNIT_OPTIONS = [
  { value: "KB", label: "KB" },
  { value: "MB", label: "MB" },
  { value: "GB", label: "GB" },
  { value: "TB", label: "TB" },
];

const specRows: ComponentProps<typeof IdsDataGrid>["rows"] = [
  {
    id: "r-1",
    values: {
      name: "North America Control Plane",
      type: "Service",
      status: "Active",
      amount: 3200,
      dueDate: "2026-05-30T14:00:00",
      updatedAt: "2026-05-31T11:15:00",
      owner: "Platform",
      region: "NA",
    },
  },
  {
    id: "r-2",
    values: {
      name: "Europe Billing Processor",
      type: "Job",
      status: "Warning",
      amount: 450,
      dueDate: "2026-05-28T09:30:00",
      updatedAt: "2026-05-28T09:30:00",
      owner: "Finance",
      region: "EU",
    },
  },
  {
    id: "r-3",
    values: {
      name: "Asia Analytics Stream",
      type: "Pipeline",
      status: "Active",
      amount: 8900,
      dueDate: "2026-04-15T16:45:00",
      updatedAt: "2026-04-20T08:00:00",
      owner: "Data Ops",
      region: "APAC",
    },
  },
  {
    id: "r-4",
    values: {
      name: "Archive Worker",
      type: "Worker",
      status: "Paused",
      amount: 75,
      dueDate: "2025-06-01T08:00:00",
      updatedAt: "2025-06-01T08:00:00",
      owner: "Storage",
      region: "NA",
    },
  },
  {
    id: "r-5",
    values: {
      name: "Policy Service",
      type: "Service",
      status: "Active",
      amount: 1200,
      dueDate: "2026-06-15T10:00:00",
      updatedAt: "2026-05-29T16:00:00",
      owner: "Security",
      region: "Global",
    },
  },
  {
    id: "r-6",
    values: {
      name: "Realtime Gateway",
      type: "Gateway",
      status: "Critical",
      amount: 5400,
      dueDate: "2026-05-25T18:30:00",
      updatedAt: "2026-05-30T14:00:00",
      owner: "Edge",
      region: "EU",
    },
  },
  {
    id: "r-7",
    values: {
      name: "Ingestion Adapter",
      type: "Adapter",
      status: "Active",
      amount: 2100,
      dueDate: "2026-05-31T11:15:00",
      updatedAt: "2026-05-27T12:45:00",
      owner: "Data Ops",
      region: "APAC",
    },
  },
  {
    id: "r-8",
    values: {
      name: "Partner Connector",
      type: "Connector",
      status: "Warning",
      amount: 980,
      dueDate: "2026-03-10T09:00:00",
      updatedAt: "2026-05-15T09:30:00",
      owner: "Integrations",
      region: "NA",
    },
  },
];

/**
 * Defaults from `components/ids/datagrid/design-spec.md` (Codegen variant matrix + Figma `37721:112482` container height).
 */
const specAccurateArgs: ComponentProps<typeof IdsDataGrid> = {
  columns: specColumns,
  rows: specRows,
  viewMode: "table",
  rowSelection: true,
  selectionMode: "single",
  showSingleSelectionRadio: true,
  withDetailPanel: true,
  pageSize: 6,
  readOnly: false,
  rowVerticalIndicator: true,
  headerColorAndBorder: true,
  columnResizeEnabled: true,
};

const meta: Meta<typeof IdsDataGrid> = {
  title: "Spec Generated/IDS/Datagrid",
  component: IdsDataGrid,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component: [
          `Spec-driven IDS Datagrid. Source of truth: \`${DESIGN_SPEC_PATH}\`.`,
          "Primary story uses spec defaults: `headerColorAndBorder` (Figma `colorAndBorder`), `rowVerticalIndicator` (`verticalBlueLine`), `rowSelection` + `selectionMode` + optional `showSingleSelectionRadio` (single mode only) + IDS Pagination footer, `columnResizeEnabled`, portaled L-frame filters (`37721:114635`), header `48px` / row `40px`, `Icon` + `shapeName` for sort/filter/settings.",
          "Use Storybook controls: **Selection mode** (`single` | `multiple`); in **single**, **Show single selection radio** toggles the 48px radio column. Row click activates the row / detail panel only — it does not toggle selection controls.",
        ].join(" "),
      },
    },
  },
  args: specAccurateArgs,
  argTypes: {
    rowSelection: {
      control: "boolean",
      description: "Show the 48px leading selection column.",
    },
    selectionMode: {
      control: "radio",
      options: ["single", "multiple"],
      description:
        "single = optional row radios; multiple = row checkbox + header select-all (current page). Row click does not toggle controls.",
      if: { arg: "rowSelection", truthy: true },
    },
    showSingleSelectionRadio: {
      control: "boolean",
      description:
        "When selectionMode is single: show the 48px column with per-row radios. When false, no selection column (row click / detail panel only).",
      if: { arg: "selectionMode", eq: "single" },
    },
  },
};

export default meta;
type Story = StoryObj<typeof IdsDataGrid>;

function SpecAccurateFrame(props: ComponentProps<typeof IdsDataGrid>) {
  return (
    <div
      style={{
        height: "100vh",
        boxSizing: "border-box",
        padding: 16,
        background: "var(--color-background-surface-1)",
        display: "flex",
        flexDirection: "column",
        minHeight: 0,
      }}
    >
      <div
        style={{
          flex: 1,
          minHeight: 0,
          minWidth: 0,
          display: "flex",
          flexDirection: "column",
        }}
      >
        <IdsDataGridDefaultStoryHost {...props} numericUnitOptions={DEMO_UNIT_OPTIONS} />
      </div>
    </div>
  );
}

/** Canonical reference: Figma Data Grid - Main (`37721:112482`) in a bounded container with spec default props. */
export const SpecAccurateDesign: Story = {
  name: "Spec Accurate Design",
  render: (args) => <SpecAccurateFrame {...args} />,
  args: specAccurateArgs,
};

/** Figma `colorAndBorder=false` on column header `37721:114663`. */
export const HeaderMinimal: Story = {
  render: (args) => <SpecAccurateFrame {...args} />,
  args: { ...specAccurateArgs, headerColorAndBorder: false },
};

/** Row hover uses `surface-1` (Figma `Hover on read only table`, `37721:114580`). */
export const ReadOnlyTableHover: Story = {
  render: (args) => <SpecAccurateFrame {...args} />,
  args: { ...specAccurateArgs, readOnly: true },
};

/** Selected rows without the 4px leading brand bar (`verticalBlueLine=false`). */
export const WithoutVerticalSelectionIndicator: Story = {
  render: (args) => <SpecAccurateFrame {...args} />,
  args: { ...specAccurateArgs, rowVerticalIndicator: false },
};

/** Optional `DatagridDetailPanelSlot` + row click selection (`detailsPanel: attached`). */
export const WithDetailPanel: Story = {
  render: (args) => <SpecAccurateFrame {...args} />,
  args: { ...specAccurateArgs, withDetailPanel: true, viewMode: "treeview" },
};

const numericFilterColumns: IdsDataGridColumn[] = [
  { key: "name", title: "Name", sortable: true, minWidth: 90, width: 200 },
  {
    key: "amount",
    title: "Amount",
    sortable: true,
    filterable: true,
    minWidth: 90,
    width: 120,
  },
  { key: "status", title: "Status", sortable: true, minWidth: 90, width: 120 },
];

const numericFilterRows: ComponentProps<typeof IdsDataGrid>["rows"] = [
  { id: "n-1", values: { name: "Alpha", amount: 1200, status: "Active" } },
  { id: "n-2", values: { name: "Beta", amount: 450, status: "Active" } },
  { id: "n-3", values: { name: "Gamma", amount: 8900, status: "Warning" } },
  { id: "n-4", values: { name: "Delta", amount: 75, status: "Paused" } },
  { id: "n-5", values: { name: "Epsilon", amount: 3200, status: "Active" } },
];

const dateTimeFilterColumns: IdsDataGridColumn[] = [
  { key: "name", title: "Name", sortable: true, minWidth: 90, width: 200 },
  {
    key: "updatedAt",
    title: "Updated",
    sortable: true,
    filterable: true,
    minWidth: 120,
    width: 180,
  },
  { key: "status", title: "Status", sortable: true, minWidth: 90, width: 120 },
];

const dateTimeFilterRows: ComponentProps<typeof IdsDataGrid>["rows"] = [
  {
    id: "dt-1",
    values: { name: "Alpha", updatedAt: "2026-05-30T14:00:00", status: "Active" },
  },
  {
    id: "dt-2",
    values: { name: "Beta", updatedAt: "2026-05-28T09:30:00", status: "Active" },
  },
  {
    id: "dt-3",
    values: { name: "Gamma", updatedAt: "2026-04-15T16:45:00", status: "Warning" },
  },
  {
    id: "dt-4",
    values: { name: "Delta", updatedAt: "2025-06-01T08:00:00", status: "Paused" },
  },
  {
    id: "dt-5",
    values: { name: "Epsilon", updatedAt: "2026-05-31T11:15:00", status: "Active" },
  },
];

const dateFilterColumns: IdsDataGridColumn[] = [
  { key: "name", title: "Name", sortable: true, minWidth: 90, width: 200 },
  {
    key: "dueDate",
    title: "Due Date",
    sortable: true,
    filterable: true,
    minWidth: 120,
    width: 160,
  },
  { key: "status", title: "Status", sortable: true, minWidth: 90, width: 120 },
];

const dateFilterRows: ComponentProps<typeof IdsDataGrid>["rows"] = [
  {
    id: "df-1",
    values: { name: "Alpha", dueDate: "2026-05-30T14:00:00", status: "Active" },
  },
  {
    id: "df-2",
    values: { name: "Beta", dueDate: "2026-05-28T09:30:00", status: "Active" },
  },
  {
    id: "df-3",
    values: { name: "Gamma", dueDate: "2026-04-15T16:45:00", status: "Warning" },
  },
  {
    id: "df-4",
    values: { name: "Delta", dueDate: "2025-06-01T08:00:00", status: "Paused" },
  },
  {
    id: "df-5",
    values: { name: "Epsilon", dueDate: "2026-05-31T11:15:00", status: "Active" },
  },
];

/** Figma date filter `37822:90838` — preset radios + DatePicker only (`37822:90904`, `37822:90922`). */
export const DateColumnFilter: Story = {
  name: "Date Column Filter",
  render: () => (
    <div
      style={{
        height: "100vh",
        boxSizing: "border-box",
        padding: 16,
        background: "var(--color-background-surface-1)",
        display: "flex",
        flexDirection: "column",
        minHeight: 0,
      }}
    >
      <div style={{ flex: 1, minHeight: 0, minWidth: 0, display: "flex", flexDirection: "column" }}>
        <IdsDataGridDateFilterStoryHost
          columns={dateFilterColumns}
          rows={dateFilterRows}
          rowSelection={false}
          withDetailPanel={false}
          pageSize={10}
          headerColorAndBorder
        />
      </div>
    </div>
  ),
};

/** Figma date-time filter `44360:181306` — preset radios + DatePicker/TimePicker (`44360:181372`, `44360:181390`). */
export const DateAndTimeColumnFilter: Story = {
  name: "Date and Time Column Filter",
  render: () => (
    <div
      style={{
        height: "100vh",
        boxSizing: "border-box",
        padding: 16,
        background: "var(--color-background-surface-1)",
        display: "flex",
        flexDirection: "column",
        minHeight: 0,
      }}
    >
      <div style={{ flex: 1, minHeight: 0, minWidth: 0, display: "flex", flexDirection: "column" }}>
        <IdsDataGridDateAndTimeFilterStoryHost
          columns={dateTimeFilterColumns}
          rows={dateTimeFilterRows}
          rowSelection={false}
          withDetailPanel={false}
          pageSize={10}
          headerColorAndBorder
        />
      </div>
    </div>
  ),
};

/** Figma numeric filter `44360:182265` — operator list + value fields (`44367:182637`, `44370:145919`); unit dropdown `44370:145922`. */
export const NumericColumnFilter: Story = {
  name: "Numeric Column Filter",
  render: () => (
    <div
      style={{
        height: "100vh",
        boxSizing: "border-box",
        padding: 16,
        background: "var(--color-background-surface-1)",
        display: "flex",
        flexDirection: "column",
        minHeight: 0,
      }}
    >
      <div style={{ flex: 1, minHeight: 0, minWidth: 0, display: "flex", flexDirection: "column" }}>
        <IdsDataGridNumericFilterStoryHost
          columns={numericFilterColumns}
          rows={numericFilterRows}
          rowSelection={false}
          withDetailPanel={false}
          pageSize={10}
          headerColorAndBorder
          numericUnitOptions={DEMO_UNIT_OPTIONS}
        />
      </div>
    </div>
  ),
};

const specTokens = [
  "--color-background-component",
  "--color-background-surface-1",
  "--color-background-gray-neutral-lighter",
  "--color-background-brand-lighter",
  "--color-background-brand-light",
  "--color-border-light",
  "--color-border-accessible",
  "--color-border-brand-base",
  "--color-text-neutral-strong",
  "--color-text-neutral",
  "--color-icon-neutral",
  "--color-icon-brand-base",
  "--color-icon-brand-stronger",
] as const;

const specTokenRefs: Record<string, string[]> = {
  "--color-background-component": [
    "Layout: default row fill on each body cell",
    "States: DatagridHeader colorAndBorder=false",
    "FilterMenu: FilterIconTab background",
  ],
  "--color-background-surface-1": ["States: DatagridRow hover on read-only table"],
  "--color-background-gray-neutral-lighter": ["States: DatagridHeader colorAndBorder=true"],
  "--color-background-brand-lighter": ["States: DatagridRow hover / selected"],
  "--color-background-brand-light": ["States: DatagridRow selected and press"],
  "--color-border-light": ["Layout: row bottom divider; header rails and band borders"],
  "--color-border-accessible": ["Column filter L-frame outer border"],
  "--color-border-brand-base": ["Row vertical selection accent (4px leading bar)"],
  "--color-text-neutral-strong": ["Layout: column title Body 2 - Medium"],
  "--color-text-neutral": ["Layout: body cell text"],
  "--color-icon-neutral": ["States: SortToggle default; FilterToggle default/hover"],
  "--color-icon-brand-base": ["States: SortToggle selected; FilterToggle selected"],
  "--color-icon-brand-stronger": ["States: FilterToggle press"],
};

export const TokenInspector: Story = {
  render: () => (
    <div className="sbTokenInspector">
      <style>{`
        .sbTokenInspector {
          display: grid;
          gap: 8px;
          max-width: 880px;
          padding: 16px;
        }
        .sbTokenHeader {
          font-size: 12px;
          opacity: 0.8;
        }
        .sbTokenRow {
          display: grid;
          grid-template-columns: minmax(260px, 1fr) 72px 120px minmax(260px, 1fr);
          align-items: start;
          gap: 12px;
          padding: 6px 8px;
          border: 1px solid var(--color-border-light);
          border-radius: 4px;
          background: var(--color-background-component);
        }
        .sbTokenCode {
          font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
          font-size: 12px;
        }
        .sbTokenSwatch {
          width: 64px;
          height: 20px;
          border: 1px solid var(--color-border-accessible);
          border-radius: 2px;
        }
        .sbTokenSample {
          font-size: 12px;
        }
        .sbTokenRefs {
          display: grid;
          gap: 2px;
          font-size: 11px;
          opacity: 0.9;
        }
      `}</style>
      <div className="sbTokenHeader">{`Token inspector — ${DESIGN_SPEC_PATH}`}</div>
      {specTokens.map((token) => (
        <div key={token} className="sbTokenRow">
          <span className="sbTokenCode">{`var(${token})`}</span>
          <span className="sbTokenSwatch" style={{ background: `var(${token})` }} />
          <span className="sbTokenSample" style={{ color: `var(${token})` }}>
            Sample
          </span>
          <div className="sbTokenRefs">
            {(specTokenRefs[token] ?? []).map((ref) => (
              <div key={ref}>{ref}</div>
            ))}
          </div>
        </div>
      ))}
    </div>
  ),
};
