/* @generated by strict-spec-storybook-gate */
/* component: dropdown-single-select */
/* spec_hash: a05e7fd9cf70f7b2c308b4fa18309cd8157213f95453c8088d085725ce01356e */
import React from "react";
import "../../../../components/ids-theme.css";
import type { Meta, StoryObj } from "@storybook/react";
import { useMemo, useState } from "react";
import { DropdownMenu as IdsDropdownSingleSelect } from "../../../../storybook/src/components/DropdownMenu";
import { IdsDropdownTriggerShell } from "../../../../storybook/src/components/IdsDropdownTriggerShell";

type Option = { id: string; label: string; disabled?: boolean };

const options: Option[] = [
  { id: "o1", label: "Option 1" },
  { id: "o2", label: "Option 2" },
  { id: "o3", label: "Option 3", disabled: true },
  { id: "o4", label: "Option 4" },
  { id: "o5", label: "Option 5" },
];

const meta: Meta<typeof IdsDropdownSingleSelect> = {
  title: "Spec Generated/IDS/Dropdown/Single Select",
  component: IdsDropdownSingleSelect,
  parameters: { layout: "centered" },
  argTypes: {
    showSingleSelectRadio: { control: "boolean" },
  },
};

export default meta;
type Story = StoryObj<typeof IdsDropdownSingleSelect>;

function Trigger({ value, placeholder = "-Select-", disabled = false, error = false }: {
  value?: string;
  placeholder?: string;
  disabled?: boolean;
  error?: boolean;
}) {
  return (
    <IdsDropdownTriggerShell
      disabled={disabled}
      error={error}
      filled={Boolean(value)}
      left={
        <span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
          {value || placeholder}
        </span>
      }
    />
  );
}

export const Playground: Story = {
  args: { showSingleSelectRadio: true },
  render: (args) => {
    const [selected, setSelected] = useState("Option 2");
    const items = useMemo(
      () =>
        options.map((option) => ({
          id: option.id,
          value: option.label,
          label: option.label,
          selectable: true,
          disabled: option.disabled,
          onClick: () => !option.disabled && setSelected(option.label),
        })),
      [],
    );
    return (
      <IdsDropdownSingleSelect
        trigger={<Trigger value={selected} />}
        items={items}
        selectionMode="single"
        selectedValues={[selected]}
        showSingleSelectRadio={args.showSingleSelectRadio}
        defaultOpen
      />
    );
  },
};

export const States: Story = {
  args: { showSingleSelectRadio: true },
  render: (args) => (
    <div style={{ display: "grid", gap: 16, width: 320 }}>
      <IdsDropdownSingleSelect
        trigger={<Trigger value="Option 2" />}
        items={options.map((o) => ({ id: o.id, value: o.label, label: o.label, selectable: true, disabled: o.disabled }))}
        selectionMode="single"
        selectedValues={["Option 2"]}
        showSingleSelectRadio={args.showSingleSelectRadio}
      />
      <IdsDropdownSingleSelect
        trigger={<Trigger value="Option 2" disabled />}
        items={options.map((o) => ({ id: o.id, value: o.label, label: o.label, selectable: true, disabled: o.disabled }))}
        selectionMode="single"
        selectedValues={["Option 2"]}
        showSingleSelectRadio={args.showSingleSelectRadio}
        disabled
      />
      <IdsDropdownSingleSelect
        trigger={<Trigger placeholder="-Type or Select-" error />}
        items={options.map((o) => ({ id: o.id, value: o.label, label: o.label, selectable: true, disabled: o.disabled }))}
        selectionMode="single"
        showSingleSelectRadio={args.showSingleSelectRadio}
      />
    </div>
  ),
};

const specTokens = ["--padding-padding-16", "--padding-padding-10", "--padding-padding-6", "--padding-padding-1", "--padding-padding-24", "--border-width-border-default", "--color-background-surface-component", "--color-border-gray-neutral-base", "--color-border-gray-neutral-strong", "--color-border-brand-base", "--color-border-gray-disabled", "--color-text-gray-neutral", "--color-text-gray-neutral-strong", "--color-text-gray-disabled", "--color-background-gray-lighter", "--color-background-controls-lighter", "--color-background-controls-base", "--color-background-controls-strong", "--color-text-brand-strong", "--color-border-brand-transparent-brand", "--color-icon-gray-white", "--color-icon-gray-neutral-accessible", "--color-icon-gray-neutral-base", "--color-icon-gray-disabled", "--color-border-alerting-critical-base", "--color-icon-alerting-critical-base", "--color-text-alerting-critical-base", "--corner-radius-radius-2", "--corner-radius-radius-4", "--spacing-space-8"] as const;
const specTokenRefs = {
  "--padding-padding-16": ["Layout: field + option horizontal padding"],
  "--padding-padding-10": ["Layout: large field vertical padding, option vertical padding"],
  "--padding-padding-6": ["Layout: small field vertical padding"],
  "--padding-padding-1": ["Geometry: caret horizontal padding"],
  "--padding-padding-24": ["Geometry: option right padding"],
  "--border-width-border-default": ["Geometry: field + menu border width (1px)"],
  "--color-background-surface-component": ["States: field default/hover/show-dropdown/focus/error bg", "States: option default bg"],
  "--color-border-gray-neutral-base": ["States: field default/show-dropdown/focus-visible (inner) border"],
  "--color-border-gray-neutral-strong": ["States: field hover border"],
  "--color-border-brand-base": ["States: field focus-visible outer ring"],
  "--color-border-gray-disabled": ["States: field disabled border"],
  "--color-text-gray-neutral": ["States: field default/hover/show-dropdown/focus/error text", "States: option default/hover text"],
  "--color-text-gray-neutral-strong": ["Tokens: label text"],
  "--color-text-gray-disabled": ["States: field disabled text"],
  "--color-background-gray-lighter": ["States: field disabled bg", "States: option disabled bg"],
  "--color-background-controls-lighter": ["States: option hover bg"],
  "--color-background-controls-base": ["States: radio/checkbox selected fill"],
  "--color-background-controls-strong": ["States: radio/checkbox selected hover fill"],
  "--color-text-brand-strong": ["States: option selected text"],
  "--color-border-brand-transparent-brand": ["States: checkbox selected border"],
  "--color-icon-gray-white": ["States: checkbox selected tick colour"],
  "--color-icon-gray-neutral-accessible": ["Asset: caret (legacy)"],
  "--color-icon-gray-neutral-base": ["Asset: caret default/hover/focus/show-dropdown/error"],
  "--color-icon-gray-disabled": ["Asset: caret disabled"],
  "--color-border-alerting-critical-base": ["States: field error border"],
  "--color-icon-alerting-critical-base": ["States: error icon colour"],
  "--color-text-alerting-critical-base": ["States: error text colour"],
  "--corner-radius-radius-2": ["Geometry: checkbox corner radius"],
  "--corner-radius-radius-4": ["Geometry: focus ring border-radius"],
  "--spacing-space-8": ["Geometry: option gap, label gap"],
} as Record<string, string[]>;

export const TokenInspector: Story = {
  render: () => (
    <div className="sbTokenInspector">
      <style>{
        `
        .sbTokenInspector {
          display: grid;
          gap: 8px;
          max-width: 880px;
        }
        .sbTokenHeader {
          font-size: 12px;
          opacity: 0.8;
        }
        .sbTokenRow {
          display: grid;
          grid-template-columns: minmax(260px, 1fr) 72px 120px minmax(260px, 1fr);
          align-items: start;
          gap: 12px;
          padding: 6px 8px;
          border: 1px solid var(--color-border-neutral-light, #c5c5c5);
          border-radius: 4px;
          background: var(--color-background-surface-component, #ffffff);
        }
        .sbTokenCode {
          font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
          font-size: 12px;
          white-space: nowrap;
          overflow: hidden;
          text-overflow: ellipsis;
        }
        .sbTokenSwatch {
          width: 64px;
          height: 20px;
          border: 1px solid var(--color-border-gray-neutral-base, #757575);
          border-radius: 2px;
          background: transparent;
        }
        .sbTokenSample {
          font-size: 12px;
          white-space: nowrap;
        }
        .sbTokenRefs {
          display: grid;
          gap: 2px;
          font-size: 11px;
          line-height: 16px;
          opacity: 0.9;
        }
        .sbTokenRef {
          white-space: nowrap;
          overflow: hidden;
          text-overflow: ellipsis;
        }
        `
      }</style>
      <div className="sbTokenHeader">Spec token inspector (name + live preview + where token is referenced in spec)</div>
      {specTokens.map((token) => (
        <div key={token} className="sbTokenRow">
          <span className="sbTokenCode">{`var(${token})`}</span>
          <span className="sbTokenSwatch" style={{ background: `var(${token})` }} />
          <span className="sbTokenSample" style={{ color: `var(${token})` }}>Sample</span>
          <div className="sbTokenRefs">
            {(specTokenRefs[token] || []).slice(0, 3).map((ref, idx) => (
              <div key={`${token}-${idx}`} className="sbTokenRef" title={ref}>{ref}</div>
            ))}
            {(specTokenRefs[token] || []).length === 0 ? <div className="sbTokenRef">No direct spec reference found</div> : null}
            {(specTokenRefs[token] || []).length > 3 ? (
              <div className="sbTokenRef">+{(specTokenRefs[token] || []).length - 3} more</div>
            ) : null}
          </div>
        </div>
      ))}
    </div>
  ),
};

