/* @generated by strict-spec-storybook-gate */
/* component: radio-button */
/* spec_hash: a6cdebd11c86c29551bc3702a6a45c4d74b0192f63262e4651b09317064b9427 */
import React from "react";
import "../../../../components/ids-theme.css";
import type { Meta, StoryObj } from "@storybook/react";
import { useState } from "react";
import { RadioButton as IdsRadioButton } from "../../../../storybook/src/components/RadioButton";

const defaultOptions = [
  { value: "option1", label: "Option 1" },
  { value: "option2", label: "Option 2" },
  { value: "option3", label: "Option 3" },
];

const FIGMA_OPTION_LABEL = "Option";
const MATRIX_VALUE = "v";

const sharedRadioStoryStyles = `
  .sbRadioRow {
    display: flex;
    gap: 40px;
    flex-wrap: wrap;
    align-items: flex-start;
  }
  .sbRadioCol {
    display: grid;
    gap: 20px;
  }
  .sbRadioMatrixSection {
    display: flex;
    flex-direction: column;
    gap: 12px;
    min-width: 200px;
  }
  .sbRadioSectionTitle {
    font-size: 11px;
    font-weight: 600;
    letter-spacing: 0.05em;
    text-transform: uppercase;
    margin: 0;
    opacity: 0.72;
    border-bottom: 1px solid var(--color-border-accessible, #757575);
    padding-bottom: 8px;
  }
  .sbHarness {
    display: grid;
    grid-template-columns: 118px repeat(4, minmax(132px, max-content));
    gap: 16px 22px;
    align-items: start;
  }
  .sbHarnessLegend {
    grid-column: 1 / -1;
    font-size: 13px;
    line-height: 1.45;
    margin: 0 0 10px;
    max-width: 860px;
  }
  .sbHarnessCorner {
    min-height: 4px;
  }
  .sbHarnessHeader {
    font-size: 10px;
    font-weight: 600;
    letter-spacing: 0.05em;
    text-transform: uppercase;
    opacity: 0.72;
    padding-bottom: 6px;
    border-bottom: 1px solid var(--color-border-accessible, #757575);
  }
  .sbHarnessTitle {
    font-size: 12px;
    font-weight: 600;
    opacity: 0.85;
    padding-top: 6px;
  }
  .sbHarnessControl {
    display: flex;
    flex-direction: column;
    gap: 6px;
    justify-content: flex-start;
    min-height: 40px;
  }
  .sbHarnessHint {
    font-size: 10px;
    line-height: 1.25;
    opacity: 0.62;
    max-width: 152px;
  }
  .sbHarnessFull {
    grid-column: 1 / -1;
    padding-top: 8px;
    border-top: 1px solid var(--color-border-accessible, #757575);
    margin-top: 4px;
  }
  .sbHarnessFullTitle {
    font-size: 12px;
    font-weight: 600;
    opacity: 0.85;
    margin: 0 0 12px;
  }
  .sbValueText {
    font-size: 14px;
    line-height: 1.4;
  }
`;

const meta: Meta<typeof IdsRadioButton> = {
  title: "Spec Generated/IDS/Radio Button",
  component: IdsRadioButton,
  parameters: { layout: "padded" },
  decorators: [
    (Story) => (
      <>
        <style>{sharedRadioStoryStyles}</style>
        <Story />
      </>
    ),
  ],
  argTypes: {
    orientation: { control: "select", options: ["vertical", "horizontal"] },
    disabled: { control: "boolean" },
  },
  args: {
    name: "ids-radio-default",
    options: defaultOptions,
    defaultValue: "option1",
    disabled: false,
  },
};

export default meta;
type Story = StoryObj<typeof IdsRadioButton>;

export const Playground: Story = {
  render: (args) => <IdsRadioButton {...args} />,
};

export const SelectionStates: Story = {
  render: () => (
    <div className="sbRadioRow">
      <div className="sbRadioMatrixSection">
        <h3 className="sbRadioSectionTitle">No selection</h3>
        <IdsRadioButton
          name="ids-radio-sel-none"
          options={[
            { value: "a", label: FIGMA_OPTION_LABEL },
            { value: "b", label: `${FIGMA_OPTION_LABEL} B` },
            { value: "c", label: `${FIGMA_OPTION_LABEL} C` },
          ]}
        />
        <p className="sbHarnessHint" style={{ margin: 0 }}>
          Hover any control for strong border.
        </p>
      </div>
      <div className="sbRadioMatrixSection">
        <h3 className="sbRadioSectionTitle">With selection</h3>
        <IdsRadioButton
          name="ids-radio-sel-one"
          defaultValue="a"
          options={[
            { value: "a", label: FIGMA_OPTION_LABEL },
            { value: "b", label: `${FIGMA_OPTION_LABEL} B` },
            { value: "c", label: `${FIGMA_OPTION_LABEL} C` },
          ]}
        />
      </div>
      <div className="sbRadioMatrixSection">
        <h3 className="sbRadioSectionTitle">Simulated (docs)</h3>
        <IdsRadioButton
          name="ids-radio-sim"
          options={[
            { value: "h", label: "Hover (simulated)", simulatedState: "hover" },
            { value: "f", label: "Focus (simulated)", simulatedState: "focus-visible" },
            { value: "d", label: "Disabled", disabled: true },
          ]}
        />
      </div>
    </div>
  ),
};

export const SelectedDisabled: Story = {
  render: () => (
    <IdsRadioButton
      name="ids-radio-selected-disabled-only"
      options={[{ value: "selected-disabled", label: "Selected + Disabled", disabled: true }]}
      defaultValue="selected-disabled"
    />
  ),
};


export const ValidationAndHelperText: Story = {
  render: () => (
    <div className="sbRadioCol">
      <IdsRadioButton
        name="ids-radio-helper"
        options={[
          { value: "option1", label: "Option 1", helperText: "Recommended option." },
          { value: "option2", label: "Option 2" },
          { value: "option3", label: "Option 3" },
        ]}
        defaultValue="option1"
      />
      <IdsRadioButton
        name="ids-radio-error-unselected"
        options={[
          {
            value: "option1",
            label: "Option 1",
            error: true,
            helperText: "Error message — ring stays strong border, not critical red.",
          },
          { value: "option2", label: "Option 2" },
          { value: "option3", label: "Option 3" },
        ]}
      />
      <IdsRadioButton
        name="ids-radio-error-selected"
        options={[
          {
            value: "option1",
            label: "Option 1",
            error: true,
            helperText: "Error message only — selected dot keeps brand tokens.",
          },
          { value: "option2", label: "Option 2" },
          { value: "option3", label: "Option 3" },
        ]}
        defaultValue="option1"
      />
    </div>
  ),
};

export const ControlledExample: Story = {
  render: () => {
    const [selected, setSelected] = useState("option1");
    return (
      <div className="sbRadioCol">
        <IdsRadioButton
          name="ids-radio-controlled"
          value={selected}
          onChange={setSelected}
          options={defaultOptions}
        />
        <div className="sbValueText">Selected value: {selected}</div>
      </div>
    );
  },
};

export const StateHarness: Story = {
  render: () => (
    <div className="sbHarness">
      <div className="sbHarnessLegend">
        Each cell is a single-option group. Columns: Default, Hover (pointer), Focus (<code>simulatedState</code>), Disabled.
      </div>

      <div className="sbHarnessCorner" />
      <div className="sbHarnessHeader">Default</div>
      <div className="sbHarnessHeader">Hover</div>
      <div className="sbHarnessHeader">Focus</div>
      <div className="sbHarnessHeader">Disabled</div>

      <div className="sbHarnessTitle">Unselected</div>
      <div className="sbHarnessControl">
        <IdsRadioButton name="ids-rh-u-def" options={[{ value: MATRIX_VALUE, label: FIGMA_OPTION_LABEL }]} />
      </div>
      <div className="sbHarnessControl">
        <IdsRadioButton name="ids-rh-u-hov" options={[{ value: MATRIX_VALUE, label: FIGMA_OPTION_LABEL }]} />
        <span className="sbHarnessHint">Hover the radio.</span>
      </div>
      <div className="sbHarnessControl">
        <IdsRadioButton
          name="ids-rh-u-foc"
          options={[{ value: MATRIX_VALUE, label: FIGMA_OPTION_LABEL, simulatedState: "focus-visible" }]}
        />
      </div>
      <div className="sbHarnessControl">
        <IdsRadioButton
          name="ids-rh-u-dis"
          options={[{ value: MATRIX_VALUE, label: FIGMA_OPTION_LABEL, disabled: true }]}
        />
      </div>
      <div className="sbHarnessTitle">Selected</div>
      <div className="sbHarnessControl">
        <IdsRadioButton
          name="ids-rh-s-def"
          defaultValue={MATRIX_VALUE}
          options={[{ value: MATRIX_VALUE, label: FIGMA_OPTION_LABEL }]}
        />
      </div>
      <div className="sbHarnessControl">
        <IdsRadioButton
          name="ids-rh-s-hov"
          defaultValue={MATRIX_VALUE}
          options={[{ value: MATRIX_VALUE, label: FIGMA_OPTION_LABEL }]}
        />
        <span className="sbHarnessHint">Hover for strong border + dot.</span>
      </div>
      <div className="sbHarnessControl">
        <IdsRadioButton
          name="ids-rh-s-foc"
          defaultValue={MATRIX_VALUE}
          options={[{ value: MATRIX_VALUE, label: FIGMA_OPTION_LABEL, simulatedState: "focus-visible" }]}
        />
      </div>
      <div className="sbHarnessControl">
        <IdsRadioButton
          name="ids-rh-s-dis"
          defaultValue={MATRIX_VALUE}
          options={[{ value: MATRIX_VALUE, label: FIGMA_OPTION_LABEL, disabled: true }]}
        />
      </div>
      <div className="sbHarnessFull">
        <p className="sbHarnessFullTitle">Selected + disabled (single control)</p>
        <IdsRadioButton
          name="ids-rh-sd"
          defaultValue={MATRIX_VALUE}
          options={[{ value: MATRIX_VALUE, label: FIGMA_OPTION_LABEL, disabled: true }]}
        />
      </div>

    </div>
  ),
};

export const LayoutTokens: Story = {
  render: () => (
    <div className="sbRadioCol" style={{ maxWidth: 560 }}>
      <p style={{ fontSize: 13, margin: 0, lineHeight: 1.5 }}>
        Spacing helpers load via <code>meta.decorators</code> (<code>.sbRadioRow</code>, <code>.sbHarness</code>, …).
      </p>
      <div className="sbRadioRow">
        <IdsRadioButton name="ids-radio-layout-a" options={defaultOptions} defaultValue="option1" />
      </div>
    </div>
  ),
};
