/* @generated by strict-spec-storybook-gate */
/* component: toast */
/* spec_hash: f0c002a94fb80e54d7f82be159a4e01cbb2c10f596cee5255843ce481a7db338 */
import type { Meta, StoryObj } from "@storybook/react";
import {
  ToastSetup,
  type ToastPosition,
  type ToastVariant,
  useToast,
} from "../../../../storybook/src/components/Toast";
import { IdsButton } from "../../../../storybook/src/components/IdsButton";

interface ToastStoryArgs {
  variant: ToastVariant;
  message: string;
  showLink: boolean;
  closable: boolean;
  linkLabel: string;
  position: ToastPosition;
  duration: number;
}

const meta: Meta<ToastStoryArgs> = {
  title: "Spec Generated/IDS/Toast",
  args: {
    variant: "info",
    message: "This is a temporary and brief notification following a user action.",
    showLink: true,
    closable: true,
    linkLabel: "View Details",
    position: "top-right",
    duration: 8000,
  },
  argTypes: {
    variant: {
      control: "select",
      options: ["info", "critical", "major-warning", "minor-warning", "success"],
    },
    message: { control: "text" },
    showLink: { control: "boolean" },
    closable: { control: "boolean" },
    linkLabel: { control: "text" },
    position: {
      control: "select",
      options: [
        "top-left",
        "top-center",
        "top-right",
        "bottom-left",
        "bottom-center",
        "bottom-right",
      ],
    },
    duration: { control: { type: "number", min: 0, step: 500 } },
  },
  decorators: [
    (Story, ctx) => (
      <ToastSetup position={ctx.args.position} duration={ctx.args.duration}>
        <Story />
      </ToastSetup>
    ),
  ],
};

export default meta;
type Story = StoryObj<ToastStoryArgs>;

function getToastType(variant: ToastVariant): "info" | "success" | "warning" | "error" {
  if (variant === "critical") return "error";
  if (variant === "success") return "success";
  if (variant === "info") return "info";
  return "warning";
}

function ToastDemo(args: ToastStoryArgs) {
  const toastManager = useToast();
  const { variant, message, showLink, closable, linkLabel, duration } = args;

  const showToast = () => {
    toastManager.add({
      description: message,
      type: getToastType(variant),
      data: {
        variant,
        showLink,
        closable,
        linkLabel,
        duration,
      },
    });
  };

  return (
    <div className="sbToastRow">
      <IdsButton variant="secondary" onClick={showToast}>
        Show Toast
      </IdsButton>
    </div>
  );
}

export const Playground: Story = {
  render: (args) => <ToastDemo {...args} />,
};

export const AlertingTypes: Story = {
  args: {
    closable: false,
  },
  render: () => {
    const toastManager = useToast();
    const variants: ToastVariant[] = [
      "info",
      "critical",
      "major-warning",
      "minor-warning",
      "success",
    ];
    return (
      <div className="sbToastRow">
        {variants.map((variant) => (
          <IdsButton
            key={variant}
            variant="secondary"
            onClick={() =>
              toastManager.add({
                description: `${variant[0].toUpperCase()}${variant.slice(1)} toast`,
                type: getToastType(variant),
                data: {
                  variant,
                  showLink: true,
                  closable: true,
                  linkLabel: "View Details",
                },
              })
            }
          >
            {variant}
          </IdsButton>
        ))}
      </div>
    );
  },
};

export const QueueAndStack: Story = {
  args: {
    showLink: false,
    closable: true,
  },
  render: (args) => {
    const toastManager = useToast();
    const variants: ToastVariant[] = [
      "info",
      "critical",
      "major-warning",
      "minor-warning",
      "success",
    ];

    const enqueueFive = () => {
      variants.forEach((variant, index) => {
        toastManager.add({
          description: `Queue item ${index + 1}: ${variant}`,
          type: getToastType(variant),
          data: {
            variant,
            showLink: args.showLink,
            closable: args.closable,
            linkLabel: args.linkLabel,
            duration: args.duration,
          },
        });
      });
    };

    return (
      <div className="sbToastRow">
        <IdsButton variant="secondary" onClick={enqueueFive}>
          Enqueue 5 Toasts
        </IdsButton>
      </div>
    );
  },
};

export const PositionMatrix: Story = {
  render: () => {
    const toastManager = useToast();
    const positions: ToastPosition[] = [
      "top-left",
      "top-center",
      "top-right",
      "bottom-left",
      "bottom-center",
      "bottom-right",
    ];
    return (
      <div className="sbToastRow">
        {positions.map((position) => (
          <IdsButton
            key={position}
            variant="secondary"
            onClick={() =>
              toastManager.add({
                description: `Position demo: ${position}`,
                type: "info",
                data: {
                  variant: "info",
                  showLink: false,
                  closable: true,
                },
              })
            }
          >
            {position}
          </IdsButton>
        ))}
      </div>
    );
  },
};

export const LayoutTokens: Story = {
  render: () => (
    <style>{
      `
      .sbToastRow {
        display: flex;
        gap: 12px;
        flex-wrap: wrap;
      }
      `
    }</style>
  ),
};

const specTokens = ["--color-static-gray-900", "--color-border-white", "--color-static-gray-white", "--color-text-white", "--color-icon-white", "--color-icon-alerting-info", "--color-border-alerting-info-white", "--color-icon-alerting-critical", "--color-border-alerting-critical-white", "--color-icon-alerting-major", "--color-border-alerting-major-white", "--color-icon-alerting-minor", "--color-border-alerting-minor-transparent", "--color-icon-alerting-success", "--color-border-alerting-success-white"] as const;

export const TokenInspector: Story = {
  render: () => (
    <div className="sbTokenInspector">
      <style>{
        `
        .sbTokenInspector {
          display: grid;
          gap: 8px;
          max-width: 880px;
        }
        .sbTokenHeader {
          font-size: 12px;
          opacity: 0.8;
        }
        .sbTokenRow {
          display: grid;
          grid-template-columns: minmax(280px, 1fr) 72px 120px;
          align-items: center;
          gap: 12px;
          padding: 6px 8px;
          border: 1px solid var(--color-border-neutral-light, #c5c5c5);
          border-radius: 4px;
          background: var(--color-background-component, #ffffff);
        }
        .sbTokenCode {
          font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
          font-size: 12px;
          white-space: nowrap;
          overflow: hidden;
          text-overflow: ellipsis;
        }
        .sbTokenSwatch {
          width: 64px;
          height: 20px;
          border: 1px solid var(--color-border-accessible, #757575);
          border-radius: 2px;
          background: transparent;
        }
        .sbTokenSample {
          font-size: 12px;
          white-space: nowrap;
        }
        `
      }</style>
      <div className="sbTokenHeader">Spec token inspector (name + live resolved preview)</div>
      {specTokens.map((token) => (
        <div key={token} className="sbTokenRow">
          <span className="sbTokenCode">{`var(${token})`}</span>
          <span className="sbTokenSwatch" style={{ background: `var(${token})` }} />
          <span className="sbTokenSample" style={{ color: `var(${token})` }}>Sample</span>
        </div>
      ))}
    </div>
  ),
};

