import { IdsGetStartedComponent } from "./ids-get-started.component";
import {
  IdsGetStartedCardAnchorComponent,
  IdsGetStartedCardConfigureButtonComponent,
  IdsGetStartedCardContentPanelComponent,
  IdsGetStartedCardDescriptionComponent,
  IdsGetStartedCardIconBadgeComponent,
  IdsGetStartedCardNoteComponent,
  IdsGetStartedCardShellComponent,
  IdsGetStartedCardTitleBandComponent,
  IdsGetStartedCardTrackComponent,
  IdsGetStartedContainerComponent,
  IdsGetStartedHeroBackgroundComponent,
  IdsGetStartedHeroHeaderComponent,
  IdsGetStartedHeroHoneycombComponent,
  IdsGetStartedHeroShadowBandComponent,
  IdsGetStartedHeroSubtitleComponent,
  IdsGetStartedHeroTitleComponent,
  IdsGetStartedMastheadSlotComponent,
  IdsGetStartedOverflowArrowComponent,
  IdsGetStartedOverflowEdgeComponent,
  IdsGetStartedOverflowGradientComponent,
  IdsGetStartedOverflowNavButtonComponent,
  IdsGetStartedSkipButtonComponent,
} from "./ids-get-started-slots.component";
import { IdsButtonComponent } from "../button/ids-button.component";
import { IdsIconComponent } from "../icon/ids-icon.component";

export const IDS_GET_STARTED_IMPORTS = [
  IdsGetStartedComponent,
  IdsGetStartedHeroHeaderComponent,
  IdsGetStartedHeroBackgroundComponent,
  IdsGetStartedHeroShadowBandComponent,
  IdsGetStartedHeroHoneycombComponent,
  IdsGetStartedMastheadSlotComponent,
  IdsGetStartedHeroTitleComponent,
  IdsGetStartedHeroSubtitleComponent,
  IdsGetStartedContainerComponent,
  IdsGetStartedCardTrackComponent,
  IdsGetStartedCardAnchorComponent,
  IdsGetStartedCardShellComponent,
  IdsGetStartedCardIconBadgeComponent,
  IdsGetStartedCardTitleBandComponent,
  IdsGetStartedCardContentPanelComponent,
  IdsGetStartedCardDescriptionComponent,
  IdsGetStartedCardNoteComponent,
  IdsGetStartedCardConfigureButtonComponent,
  IdsGetStartedSkipButtonComponent,
  IdsGetStartedOverflowEdgeComponent,
  IdsGetStartedOverflowGradientComponent,
  IdsGetStartedOverflowArrowComponent,
  IdsGetStartedOverflowNavButtonComponent,
  IdsIconComponent,
  IdsButtonComponent,
] as const;

export {
  IdsGetStartedComponent,
  IdsGetStartedHeroHeaderComponent,
  IdsGetStartedHeroBackgroundComponent,
  IdsGetStartedHeroShadowBandComponent,
  IdsGetStartedHeroHoneycombComponent,
  IdsGetStartedMastheadSlotComponent,
  IdsGetStartedHeroTitleComponent,
  IdsGetStartedHeroSubtitleComponent,
  IdsGetStartedContainerComponent,
  IdsGetStartedCardTrackComponent,
  IdsGetStartedCardAnchorComponent,
  IdsGetStartedCardShellComponent,
  IdsGetStartedCardIconBadgeComponent,
  IdsGetStartedCardTitleBandComponent,
  IdsGetStartedCardContentPanelComponent,
  IdsGetStartedCardDescriptionComponent,
  IdsGetStartedCardNoteComponent,
  IdsGetStartedCardConfigureButtonComponent,
  IdsGetStartedSkipButtonComponent,
  IdsGetStartedOverflowEdgeComponent,
  IdsGetStartedOverflowGradientComponent,
  IdsGetStartedOverflowArrowComponent,
  IdsGetStartedOverflowNavButtonComponent,
};

export type {
  IdsGetStartedCardInput,
  IdsGetStartedCardState,
  IdsGetStartedMastheadProps,
  IdsGetStartedOverflowDirection,
  IdsGetStartedOverflowPage,
  IdsGetStartedOverflowSide,
} from "./ids-get-started.types";
