/* @generated by strict-spec-storybook-gate */
/* component: main-menu-left */
/* spec_hash: 0c3a4aeb2d07c6db6752220364478d8ce8576fd7181c739afb23bebe0cf06161 */
import { applicationConfig, moduleMetadata } from "@storybook/angular";
import { provideZoneChangeDetection } from "@angular/core";
import { SPEC_ACCURATE_DESIGN_STORY } from "../../../compiled/component-contracts/common/story-meta.js";
import { MAIN_MENU_LEFT_SPEC_ACCURATE_DEFAULTS, MAIN_MENU_LEFT_SPEC_ACCURATE_ITEMS } from "../../../compiled/component-contracts/ids/main-menu-left.contract.js";
import { IdsMainMenuLeftComponent } from "../../../compiled/lib/angular/ids/main-menu-left/ids-main-menu-left.component.js";
import { IDS_MAIN_MENU_LEFT_IMPORTS } from "../../../compiled/lib/angular/ids/main-menu-left/index.js";
import {
  MAIN_MENU_LEFT_COMPOSITION_DEMO_TEMPLATE,
  MAIN_MENU_LEFT_DOCS_DESCRIPTION,
  MAIN_MENU_LEFT_SOURCE_CODE,
  MAIN_MENU_LEFT_SPEC_ACCURATE_FRAME_TEMPLATE,
  MAIN_MENU_LEFT_STORY_FRAME_STYLES,
  MAIN_MENU_LEFT_STORY_SOURCE_CODE,
} from "./ids-main-menu-left.developer-usage.js";

/** @type {import("@storybook/angular").Meta<IdsMainMenuLeftComponent>} */
const meta = {
  title: "Components/IDS/Main Menu Left",
  component: IdsMainMenuLeftComponent,
  tags: ["autodocs"],
  decorators: [
    applicationConfig({ providers: [provideZoneChangeDetection()] }),
    moduleMetadata({ imports: [...IDS_MAIN_MENU_LEFT_IMPORTS] }),
  ],
  parameters: {
    layout: "fullscreen",
    docs: {
      canvas: { sourceState: "open" },
      description: { component: MAIN_MENU_LEFT_DOCS_DESCRIPTION },
      source: { type: "code", language: "typescript", code: MAIN_MENU_LEFT_SOURCE_CODE },
    },
  },
  argTypes: {
    expanded: { control: "boolean" },
    defaultSelectedItemId: { control: "text" },
    forceStates: { control: "boolean" },
    compositionMode: { control: "boolean" },
  },
};

export default meta;

const specAccurateArgs = {
  compositionMode: true,
  expanded: MAIN_MENU_LEFT_SPEC_ACCURATE_DEFAULTS.expanded,
  defaultSelectedItemId: MAIN_MENU_LEFT_SPEC_ACCURATE_DEFAULTS.defaultSelectedItemId,
  forceStates: false,
  ariaLabel: MAIN_MENU_LEFT_SPEC_ACCURATE_DEFAULTS.ariaLabel,
};

/** @type {import("@storybook/angular").StoryObj<IdsMainMenuLeftComponent>} */
export const SpecAccurateDesign = {
  name: SPEC_ACCURATE_DESIGN_STORY,
  parameters: {
    docs: {
      description: {
        story:
          "Composition API — deterministic Item | Group(Item → Children → secondary Items); Figma `11099:56218`.",
      },
      source: { type: "code", language: "html", code: MAIN_MENU_LEFT_STORY_SOURCE_CODE },
    },
  },
  render: (args) => ({
    props: args,
    styles: [MAIN_MENU_LEFT_STORY_FRAME_STYLES],
    template: MAIN_MENU_LEFT_SPEC_ACCURATE_FRAME_TEMPLATE,
  }),
  args: specAccurateArgs,
};

/** @type {import("@storybook/angular").StoryObj<IdsMainMenuLeftComponent>} */
export const Collapsed = {
  render: (args) => ({
    props: { ...args, expanded: false },
    styles: [MAIN_MENU_LEFT_STORY_FRAME_STYLES],
    template: MAIN_MENU_LEFT_SPEC_ACCURATE_FRAME_TEMPLATE,
  }),
  args: specAccurateArgs,
};

/** @type {import("@storybook/angular").StoryObj<IdsMainMenuLeftComponent>} */
export const PrimaryStateSnapshotMatrix = {
  render: () => ({
    styles: [MAIN_MENU_LEFT_STORY_FRAME_STYLES],
    template: `
      <div class="ids-main-menu-left-state-matrix">
        <ids-main-menu-left [compositionMode]="true" [forceStates]="true" [expanded]="true">
          <ids-main-menu-left-item itemId="default" forceState="default">
            <a href="#"><ids-main-menu-left-item-icon shapeName="home" /><span class="ids-main-menu-left__primary-label">Default</span></a>
          </ids-main-menu-left-item>
          <ids-main-menu-left-item itemId="hover" forceState="hover">
            <a href="#"><ids-main-menu-left-item-icon shapeName="home" /><span class="ids-main-menu-left__primary-label">Hover</span></a>
          </ids-main-menu-left-item>
          <ids-main-menu-left-item itemId="press" forceState="press">
            <a href="#"><ids-main-menu-left-item-icon shapeName="home" /><span class="ids-main-menu-left__primary-label">Press</span></a>
          </ids-main-menu-left-item>
          <ids-main-menu-left-item itemId="selected" forceState="selected">
            <a href="#"><ids-main-menu-left-item-icon shapeName="home" /><span class="ids-main-menu-left__primary-label">Selected</span></a>
          </ids-main-menu-left-item>
          <ids-main-menu-left-item itemId="default-focus" forceState="default-focus">
            <a href="#"><ids-main-menu-left-item-icon shapeName="home" /><span class="ids-main-menu-left__primary-label">Default focus</span></a>
          </ids-main-menu-left-item>
          <ids-main-menu-left-item itemId="selected-focus" forceState="selected-focus">
            <a href="#"><ids-main-menu-left-item-icon shapeName="home" /><span class="ids-main-menu-left__primary-label">Selected focus</span></a>
          </ids-main-menu-left-item>
        </ids-main-menu-left>
      </div>
    `,
  }),
};

/** @type {import("@storybook/angular").StoryObj<IdsMainMenuLeftComponent>} */
export const LegacyItemsAdapter = {
  name: "Legacy items[] adapter",
  render: (args) => ({
    props: { ...args, compositionMode: false },
    styles: [MAIN_MENU_LEFT_STORY_FRAME_STYLES],
    template: `
      <div class="ids-main-menu-left-story-frame">
        <ids-main-menu-left
          [compositionMode]="false"
          [items]="items"
          [expanded]="expanded"
          [defaultSelectedItemId]="defaultSelectedItemId"
        />
        <div class="ids-main-menu-left-story-canvas"><p>Legacy programmatic <code>items[]</code> API.</p></div>
      </div>
    `,
  }),
  args: {
    ...specAccurateArgs,
    compositionMode: false,
    items: MAIN_MENU_LEFT_SPEC_ACCURATE_DEFAULTS.items,
  },
};
