/* @generated by strict-spec-storybook-gate */
/* component: modal */
import { applicationConfig, moduleMetadata } from "@storybook/angular";
import { provideZoneChangeDetection } from "@angular/core";
import { SPEC_ACCURATE_DESIGN_STORY } from "../../../compiled/component-contracts/common/story-meta.js";
import {
  MODAL_FIGMA_BODY,
  MODAL_MULTI_PAGE_DEMO_PAGES,
  MODAL_SPEC_ACCURATE_DEFAULTS,
} from "../../../compiled/component-contracts/ids/modal.contract.js";
import { IdsModalComponent } from "../../../compiled/lib/angular/ids/modal/ids-modal.component.js";
import { IDS_MODAL_IMPORTS } from "../../../compiled/lib/angular/ids/modal/index.js";
import {
  MODAL_COMPOSITION_DEMO_TEMPLATE,
  MODAL_DOCS_DESCRIPTION,
  MODAL_MULTI_PAGE_TEMPLATE,
  MODAL_SINGLE_PAGE_TEMPLATE,
  MODAL_SOURCE_CODE,
  MODAL_STORY_SOURCE_CODE,
} from "./ids-modal.developer-usage.js";

/** @type {import("@storybook/angular").Meta<IdsModalComponent>} */
const meta = {
  title: "Spec Generated/IDS/Modal",
  component: IdsModalComponent,
  tags: ["autodocs"],
  decorators: [
    applicationConfig({
      providers: [provideZoneChangeDetection()],
    }),
    moduleMetadata({
      imports: [...IDS_MODAL_IMPORTS],
    }),
  ],
  parameters: {
    layout: "centered",
    docs: {
      canvas: { sourceState: "open" },
      description: { component: MODAL_DOCS_DESCRIPTION },
      source: {
        type: "code",
        language: "typescript",
        code: MODAL_SOURCE_CODE,
      },
    },
  },
  argTypes: {
    scenario: { control: "select", options: ["single-page", "multi-page", "dialog"] },
    type: {
      control: "select",
      options: ["non-alerting", "informational", "warning", "major", "critical", "destructive"],
    },
    size: { control: "select", options: ["x-small", "small", "medium", "large"] },
    title: { control: "text" },
    description: { control: "text" },
    closable: { control: "boolean" },
    scrollBar: { control: "boolean" },
    tabs: { control: "boolean" },
    footerCheckbox: { control: "boolean" },
    primaryActionLabel: { control: "text" },
    tertiaryActionLabel: { control: "text" },
    enablePrimaryAction: { control: "boolean" },
    enableTertiaryAction: { control: "boolean" },
  },
};

export default meta;

function logEvent(name) {
  return (...args) => {
    // eslint-disable-next-line no-console
    console.log(`[IDS Modal event] ${name}`, ...args);
  };
}

/** @type {import("@storybook/angular").StoryObj<IdsModalComponent>} */
export const SpecAccurateDesign = {
  name: SPEC_ACCURATE_DESIGN_STORY,
  parameters: {
    docs: {
      description: {
        story:
          "Spec Accurate Design: dialog · non-alerting · large · closable · single primary action.",
      },
      source: {
        type: "code",
        language: "html",
        code: MODAL_STORY_SOURCE_CODE,
      },
    },
  },
  render: (args) => ({
    props: {
      ...args,
      onClose: logEvent("closed"),
      onPrimary: logEvent("primaryAction"),
    },
    template: MODAL_COMPOSITION_DEMO_TEMPLATE,
  }),
  args: {
    scenario: MODAL_SPEC_ACCURATE_DEFAULTS.scenario,
    type: MODAL_SPEC_ACCURATE_DEFAULTS.type,
    size: MODAL_SPEC_ACCURATE_DEFAULTS.size,
    title: MODAL_SPEC_ACCURATE_DEFAULTS.title,
    description: MODAL_SPEC_ACCURATE_DEFAULTS.description,
    closable: MODAL_SPEC_ACCURATE_DEFAULTS.closable,
    primaryActionLabel: MODAL_SPEC_ACCURATE_DEFAULTS.primaryActionLabel,
  },
};

/** @type {import("@storybook/angular").StoryObj<IdsModalComponent>} */
export const NonAlerting = {
  render: () => ({
    props: {
      description: MODAL_FIGMA_BODY,
      onClose: logEvent("closed"),
      onPrimary: logEvent("primaryAction"),
    },
    template: MODAL_COMPOSITION_DEMO_TEMPLATE,
  }),
};

/** @type {import("@storybook/angular").StoryObj<IdsModalComponent>} */
export const WarningAndCritical = {
  render: () => ({
    props: {
      description: MODAL_FIGMA_BODY,
      log: logEvent("action"),
    },
    template: `
      <div style="display: grid; gap: 16px;">
        <div>
          <ids-button variant="secondary" size="lg" (clicked)="warning.openModal()">
            Open Warning Dialog
          </ids-button>
          <ids-modal
            #warning
            scenario="dialog"
            type="warning"
            size="large"
            (primaryAction)="log('warning-primary')"
            (tertiaryAction)="log('warning-tertiary')"
            (closed)="log('warning-close')"
          >
            <ids-modal-title>Warning</ids-modal-title>
            <ids-modal-body [description]="description">
              <div style="color: var(--color-text-gray-neutral);">
                Continue to &lt;describe the action&gt;?
              </div>
            </ids-modal-body>
            <ids-modal-footer>
              <ids-button variant="tertiary" size="lg" (clicked)="log('warning-tertiary')">
                Cancel
              </ids-button>
              <ids-button variant="primary" size="lg" (clicked)="log('warning-primary')">
                Continue
              </ids-button>
            </ids-modal-footer>
          </ids-modal>
        </div>
        <div>
          <ids-button variant="secondary" size="lg" (clicked)="critical.openModal()">
            Open Critical Dialog
          </ids-button>
          <ids-modal
            #critical
            scenario="dialog"
            type="critical"
            size="large"
            (primaryAction)="log('critical-primary')"
            (tertiaryAction)="log('critical-tertiary')"
            (closed)="log('critical-close')"
          >
            <ids-modal-title>Critical</ids-modal-title>
            <ids-modal-body description="Critical modal content." />
            <ids-modal-footer>
              <ids-button variant="tertiary" size="lg" (clicked)="log('critical-tertiary')">
                Cancel
              </ids-button>
              <ids-button variant="primary" size="lg" (clicked)="log('critical-primary')">
                Continue
              </ids-button>
            </ids-modal-footer>
          </ids-modal>
        </div>
      </div>
    `,
  }),
};

/** @type {import("@storybook/angular").StoryObj<IdsModalComponent>} */
export const SinglePageModalUsage = {
  name: "Single-Page Modal Usage",
  render: () => ({
    props: { log: logEvent("action") },
    template: MODAL_SINGLE_PAGE_TEMPLATE,
  }),
};

/** @type {import("@storybook/angular").StoryObj<IdsModalComponent>} */
export const MultiPageModalUsage = {
  name: "Multi-Page Modal Usage",
  render: () => ({
    props: {
      pages: [...MODAL_MULTI_PAGE_DEMO_PAGES],
      log: logEvent("action"),
    },
    template: MODAL_MULTI_PAGE_TEMPLATE,
  }),
};

/** @type {import("@storybook/angular").StoryObj<IdsModalComponent>} */
export const SingleAndMultiPageUsage = {
  name: "Single and Multi-Page Usage",
  render: () => ({
    props: {
      pages: [
        { id: "summary", label: "Summary", content: "Summary content" },
        { id: "details", label: "Details", content: "Details content" },
        { id: "activity", label: "Activity", content: "Activity content" },
      ],
      log: logEvent("action"),
    },
    template: `
      <div style="display: grid; gap: 16px;">
        <div>
          <ids-button variant="secondary" size="lg" (clicked)="single.openModal()">
            Open Single-Page Modal
          </ids-button>
          <ids-modal
            #single
            scenario="single-page"
            type="non-alerting"
            size="large"
            (primaryAction)="log('single-primary')"
            (tertiaryAction)="log('single-tertiary')"
          >
            <ids-modal-title>Header</ids-modal-title>
            <ids-modal-body description="Single-page modal usage.">
              <div
                style="
                  min-height: 120px;
                  border: 1px solid var(--color-border-brand-base);
                  background: var(--color-background-brand-lighter-slate);
                  padding: 16px;
                "
              >
                single page modal swap content
              </div>
            </ids-modal-body>
            <ids-modal-footer>
              <ids-button variant="tertiary" size="lg" (clicked)="log('single-tertiary')">
                Cancel
              </ids-button>
              <ids-button variant="primary" size="lg" (clicked)="log('single-primary')">
                Apply
              </ids-button>
            </ids-modal-footer>
          </ids-modal>
        </div>
        <div>
          <ids-button variant="secondary" size="lg" (clicked)="multi.openModal()">
            Open Multi-Page Modal
          </ids-button>
          <ids-modal
            #multi
            scenario="multi-page"
            type="non-alerting"
            size="large"
            [tabs]="true"
            [pages]="pages"
            (pageChange)="log('page', $event)"
            (primaryAction)="log('multi-primary')"
            (tertiaryAction)="log('multi-tertiary')"
          >
            <ids-modal-title>Header</ids-modal-title>
            <ids-modal-body description="Multi page modal usage with tabs/pages." />
            <ids-modal-footer>
              <ids-button variant="tertiary" size="lg" (clicked)="log('multi-tertiary')">
                Cancel
              </ids-button>
              <ids-button variant="primary" size="lg" (clicked)="log('multi-primary')">
                Apply
              </ids-button>
            </ids-modal-footer>
          </ids-modal>
        </div>
      </div>
    `,
  }),
};

/** @type {import("@storybook/angular").StoryObj<IdsModalComponent>} */
export const SizeMatrix = {
  render: () => ({
    props: {
      description: MODAL_FIGMA_BODY,
      sizes: ["x-small", "small", "medium", "large"],
      activeSize: "medium",
      openSize(size, modal) {
        this.activeSize = size;
        modal.openModal();
      },
    },
    template: `
      <div style="display: grid; gap: 12px;">
        @for (size of sizes; track size) {
          <ids-button variant="secondary" size="lg" (clicked)="openSize(size, modal)">
            Open {{ size }} modal
          </ids-button>
        }
        <ids-modal
          #modal
          scenario="dialog"
          type="non-alerting"
          [size]="activeSize"
        >
          <ids-modal-title>Modal size: {{ activeSize }}</ids-modal-title>
          <ids-modal-body [description]="description" />
          <ids-modal-footer>
            <ids-button variant="primary" size="lg">Close</ids-button>
          </ids-modal-footer>
        </ids-modal>
      </div>
    `,
  }),
};

/** @type {import("@storybook/angular").StoryObj<IdsModalComponent>} */
export const FooterCheckbox = {
  render: () => ({
    props: { description: MODAL_FIGMA_BODY },
    template: `
      <ids-button variant="secondary" size="lg" (clicked)="modal.openModal()">
        Open Modal with Footer Checkbox
      </ids-button>
      <ids-modal
        #modal
        scenario="single-page"
        type="non-alerting"
        size="medium"
        [footerCheckbox]="true"
      >
        <ids-modal-title>Header</ids-modal-title>
        <ids-modal-body [description]="description">
          <div style="min-height: 120px;">Content with optional footer checkbox.</div>
        </ids-modal-body>
        <ids-modal-footer>
          <ids-button variant="tertiary" size="lg">Cancel</ids-button>
          <ids-button variant="primary" size="lg">Apply</ids-button>
        </ids-modal-footer>
      </ids-modal>
    `,
  }),
};

/** @type {import("@storybook/angular").StoryObj<IdsModalComponent>} */
export const ScrollableContent = {
  render: () => ({
    props: {
      rows: Array.from({ length: 24 }, (_, index) => `Scrollable row ${index + 1}`),
    },
    template: `
      <ids-button variant="secondary" size="lg" (clicked)="modal.openModal()">
        Open Scrollable Modal
      </ids-button>
      <ids-modal
        #modal
        scenario="single-page"
        type="non-alerting"
        size="small"
        [scrollBar]="true"
      >
        <ids-modal-title>Scrollable content</ids-modal-title>
        <ids-modal-body
          description="Content region supports overflow with vertical scrollbar and bottom gradient cue."
        >
          <div style="display: grid; gap: 12px;">
            @for (row of rows; track row) {
              <p style="margin: 0; color: var(--color-text-gray-neutral);">{{ row }}</p>
            }
          </div>
        </ids-modal-body>
        <ids-modal-footer>
          <ids-button variant="tertiary" size="lg">Cancel</ids-button>
          <ids-button variant="primary" size="lg">Apply</ids-button>
        </ids-modal-footer>
      </ids-modal>
    `,
  }),
};
